const dadosDeliveryItems = [
  {"GROUP":"Couvert","ITEM":"Cesta de Pães tipo Italiano","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":8},
  {"GROUP":"Couvert","ITEM":"Pão tipo Italiano com Manteiga","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":13},
  {"GROUP":"Couvert","ITEM":"Completo de 2ª a 6ª Almoço","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Couvert","ITEM":"Completo de FinDe. Feriado e Jantar","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Couvert","ITEM":"Porção Completa com cesta de pães","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":15},
  {"GROUP":"Couvert","ITEM":"Porção completa com cesta de pães e manteiga","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":20},
  {"GROUP":"Couvert","ITEM":"Filão de Pão Tipo Italiano","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":13,"PRICE_MENU":13},
  {"GROUP":"Couvert","ITEM":"Meio Filão de Pão Tipo Italiano","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Antipasto","ITEM":"alla Roperto Tradicional","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Antipasto","ITEM":"alla Roperto Médio","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Antipasto","ITEM":"Abobrinha","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":20},
  {"GROUP":"Antipasto","ITEM":"Aliche Italiano","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":70},
  {"GROUP":"Antipasto","ITEM":"Azeitonas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":20},
  {"GROUP":"Antipasto","ITEM":"Beringela à vinagrete","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":18},
  {"GROUP":"Antipasto","ITEM":"Beringela Recheada","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24,"PRICE_MENU":28},
  {"GROUP":"Antipasto","ITEM":"Caponata","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Linguiça Calabresa","ACTIVE":"FALSO","PRICE_DELIVERY":42,"PRICE_MENU":42},
  {"GROUP":"Antipasto","ITEM":"Pasta de Pimentão Verde e Ricota","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Pimentão Rosso","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":22,"PRICE_MENU":28},
  {"GROUP":"Antipasto","ITEM":"Provolone","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Salada napolitana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Salame","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Sardela","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":27},
  {"GROUP":"Antipasto","ITEM":"Sardela - Meia Porção","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Antipasto","ITEM":"Beringela all'Inferno","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Burrata com Tomate Seco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":27,"PRICE_MENU":27},
  {"GROUP":"Antipasto","ITEM":"Burrata ao Tartufo Branco com Tomate Seco","ACTIVE":"FALSO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Antipasto","ITEM":"Tomate Seco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Saladas","ITEM":"Completa Tradicional","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Completa Individual","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Salada Completa - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Saladas","ITEM":"Salada Completa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Saladas","ITEM":"Carpaccio","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Palmito e Brócolis","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Tomate","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Tomate e Palmito - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Saladas","ITEM":"Brócolis","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Palmito","ACTIVE":"FALSO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Saladas","ITEM":"Verdes","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Saladas","ITEM":"Mista (Escarola. Tomate. palmito. Bacon. salsão e Alho) - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Saladas","ITEM":"Escarola. Salsão. Bacon & Alho - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Saladas","ITEM":"Tomate e palmito","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Saladas","ITEM":"Mista (Escarola. Tomate. Palmito. Bacon. Salsão e Alho)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Saladas","ITEM":"Escarola. Salsão. Bacon & Alho","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Sopas","ITEM":"Cappelletti in Brodo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Sopas","ITEM":"Cappelletti in Brodo - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Sopas","ITEM":"Minestrone de Legumes","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Sopas","ITEM":"Minestrone de Legumes - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Sopas","ITEM":"Canja","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Sopas","ITEM":"Canja - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Infantil","ITEM":"Espaguete com almôndega","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Infantil","ITEM":"Escalopine com espaguete","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Infantil","ITEM":"Escalope com arroz e fritas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Espaguete - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Penne - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Rigatone - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Agnolotti - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Canelone Verde - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Canelone Branco - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Lasanha - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Richitelli - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Massas","ITEM":"Fetuccine branco - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Fusilli - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Massas","ITEM":"Ravioli de Ricota - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Ravioli de Carne - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Ravioli de Mussarela de Búfala - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Gnocchi de Batata - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Massas","ITEM":"Rondelli - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Cappelletti - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Fetuccine verde - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Espaguete","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Penne","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Rigatone","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Agnolotti","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Canelloni verde","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Canelloni Branco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Lasanha","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Richitelli","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Massas","ITEM":"Fetuccine Branco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Fetuccine Verde","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Fusilli","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Massas","ITEM":"Ravioli de Ricota","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Ravioli de Carne","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Ravioli de Mussarela de Búfala","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Gnocchi de Batata","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Massas","ITEM":"Rondelli","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Cappelletti","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Agnolotti Verde com recheio de Abóbora - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Agnolotti Verde com recheio de Abóbora","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Porção Massa sem Recheio (kg)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Massas","ITEM":"Porção Masssa com Recheio (kg)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Massas Especiais","ITEM":"Espaguete Integral","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas Especiais","ITEM":"Penne sem Glúten","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Molhos","ITEM":"ao Sugo - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à Napolitana - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"ao Pesto de Nossa Familia - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"à Genovesa - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Putanesca - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"aos Quatro Queijos - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Parisiense - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Romanesca - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"Rosé - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"à Carbonara Americana - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"com Aliche (Italiano di Salerno) - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Molhos","ITEM":"ao Vongolis - Inteira","ACTIVE":"FALSO","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Molhos","ITEM":"Alho e Óleo - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à Bolonhesa - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"com Brócolis Alho e Óleo - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"à calabresa - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"Gratinado - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"com Funghi Seco - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"à Michelangelo - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Etrusca - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"ao forno - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"arrabiata - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"ao Sugo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"à Napolitana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"ao Pesto de Nossa Familia","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à Genovesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Putanesca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"aos Quatro Queijos","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Parisiense","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Romanesca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"Rosé","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à Carbonara Americana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"com Aliche (Italiano di Salerno)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Molhos","ITEM":"Alho e Óleo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"à Bolonhesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"com Brócolis Alho e Óleo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à calabresa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"Gratinado","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"com Funghi Seco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à Michelangelo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Etrusca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"ao forno","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"arrabiata","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"com Frutos do Mar (individual ou meia porção)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Molhos","ITEM":"ao Vongolis (individual ou meia porção)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"com Camarões (individual)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Molhos","ITEM":"Porção de molho ao Sugo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"Porção de molho à Bolonhesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Combinações","ITEM":"Agnolotti Gratinato - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Combinações","ITEM":"Canelone Verde ao Forno - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Combinações","ITEM":"Cappelletti à Romanesca - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Combinações","ITEM":"Fusili à Calabresa - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Combinações","ITEM":"Lasanha à Bolonhesa - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Combinações","ITEM":"Ravioli de Mussarela de Búfala à Napolitana - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":95,"PRICE_MENU":95},
  {"GROUP":"Combinações","ITEM":"Richitelle salsa Rose - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Combinações","ITEM":"Rondelle aos Quatro Queijos - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Combinações","ITEM":"Fettuccine ao Pesto - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":95,"PRICE_MENU":95},
  {"GROUP":"Combinações","ITEM":"Espaguete com Almondegas - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Combinações","ITEM":"Penne à Putanesca - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Combinações","ITEM":"Rigatone à Genovesa - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Combinações","ITEM":"Gnocchi à Michelangelo - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Combinações","ITEM":"Agnolotti Gratinato","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Combinações","ITEM":"Canelone Verde ao Forno","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Combinações","ITEM":"Cappelletti à Romanesca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Combinações","ITEM":"Fusili à Calabresa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Combinações","ITEM":"Lasanha à Bolonhesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Combinações","ITEM":"Ravioli de Mussarela de Búfala à Napolitana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Combinações","ITEM":"Richitelle Salsa Rose","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Combinações","ITEM":"Rondelle aos Quatro Queijos","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Combinações","ITEM":"Fettuccine ao Pesto","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":55,"PRICE_MENU":55},
  {"GROUP":"Combinações","ITEM":"Espaguete com Almondegas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Combinações","ITEM":"Penne à Putanesca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Combinações","ITEM":"Rigatone à Genovesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Combinações","ITEM":"Gnocchi à Michelangelo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Combinações","ITEM":"Agnolotti Verde com recheio de Abóbora Rose - Inteiro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Combinações","ITEM":"Agnolotti Verde com recheio de Abóbora Rose","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado (Médio 200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":60},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":120,"PRICE_MENU":120},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa com Arroz e Fritas  (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":140,"PRICE_MENU":140},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa com Arroz e Fritas (100g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa com Arroz e Fritas (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Alho e Óleo (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":130,"PRICE_MENU":130},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Alho e Óleo (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado com Fritas (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Filé Mignon","ITEM":"Filé com Brócolis e Arroz (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":140,"PRICE_MENU":140},
  {"GROUP":"Filé Mignon","ITEM":"Filé com Brócolis e Arroz (200g ind)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":130,"PRICE_MENU":130},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana com Arroz e Fritas (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"à parmigiana com  Arroz e Fritas (100g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"à parmigiana com  Arroz e Fritas (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Filé Mignon","ITEM":"à Roperto (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"à Pizzaiolo (400g com aliche IT di salerno)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"à Cubana (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"à Cordonbleu (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"d'Alê (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":150,"PRICE_MENU":150},
  {"GROUP":"Filé Mignon","ITEM":"d'Alê (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (100g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana (médio 200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado com fritas (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"Escalope à Vienense (400g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":150,"PRICE_MENU":150},
  {"GROUP":"Filé Mignon","ITEM":"Escalope à Vienense (200g)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Frango","ITEM":"À passarinho","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Frango","ITEM":"À passarinho - Meia Porção","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Frango","ITEM":"1/2 desossado Grelhado","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":44,"PRICE_MENU":44},
  {"GROUP":"Frango","ITEM":"1/2 desossado com Creme de Milho","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado com Purê e Champignon","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado a Cubana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado com Brócolis","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"Filé de Frango a Marietta Baderna","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Milanesa Simples","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Milanesa (Tradicional)","ACTIVE":"","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Milanesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":62,"PRICE_MENU":62},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Parmigiana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Parmigiana - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Carne","ITEM":"Ropertone","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Carne","ITEM":"Mini Ropertone com Arroz","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Carne","ITEM":"Mini Ropertone","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":55,"PRICE_MENU":55},
  {"GROUP":"Carne","ITEM":"Brachola","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":38,"PRICE_MENU":38},
  {"GROUP":"Carne","ITEM":"Almondegas - Meia Porção","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Carne","ITEM":"Almondegas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Sugestões Vegetarianas","ITEM":"Almôndegas Vegetarianas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Cabrito","ITEM":"Perna Traseira de Cabrito","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":260,"PRICE_MENU":260},
  {"GROUP":"Cabrito","ITEM":"Cabrito à caçadora - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Cabrito","ITEM":"Cabrito à caçadora","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Cabrito","ITEM":"Cabrito ao forno - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Cabrito","ITEM":"Cabrito ao forno","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Risoto","ITEM":"Risoto de Frango","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Risoto","ITEM":"Risoto de Camarão","ACTIVE":"FALSO","PRICE_DELIVERY":150,"PRICE_MENU":150},
  {"GROUP":"Risoto","ITEM":"Risoto de Funghi Seco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Risoto","ITEM":"Risoto de Frutos do Mar","ACTIVE":"FALSO","PRICE_DELIVERY":120,"PRICE_MENU":120},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada à Dorê com Molho de Camarões","ACTIVE":"FALSO","PRICE_DELIVERY":81,"PRICE_MENU":81},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada à Dorê com Molho de Camarões - Inteira","ACTIVE":"FALSO","PRICE_DELIVERY":135,"PRICE_MENU":135},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada à Dorê","ACTIVE":"FALSO","PRICE_DELIVERY":51,"PRICE_MENU":51},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada à Dorê - Inteira","ACTIVE":"FALSO","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Outros","ITEM":"Beringela à Parmegiana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Outros","ITEM":"Beringela à Parmegiana - Inteira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":88,"PRICE_MENU":88},
  {"GROUP":"Outros","ITEM":"Combinado","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":90},
  {"GROUP":"Porções","ITEM":"Polenta frita","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porções","ITEM":"Arroz","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porções","ITEM":"Arroz à grega","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":34,"PRICE_MENU":34},
  {"GROUP":"Porções","ITEM":"Batata frita","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":27,"PRICE_MENU":27},
  {"GROUP":"Porções","ITEM":"Purê de batatas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Porções","ITEM":"Creme de milho","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Porções","ITEM":"Bananas à Milanesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porções","ITEM":"Brócolis Alho e Óleo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Porções","ITEM":"Brócolis com Catupiry","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Doces","ITEM":"Panna Cotta","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Doces","ITEM":"Pastiera de Grão","ACTIVE":"FALSO","PRICE_DELIVERY":18,"PRICE_MENU":18},
  {"GROUP":"Doces","ITEM":"Petit Gateau","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Doces","ITEM":"Tiramissù","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Doces","ITEM":"Tiramissù - Grande","ACTIVE":"FALSO","PRICE_DELIVERY":18,"PRICE_MENU":18},
  {"GROUP":"Doces","ITEM":"Torta Sonho de Valsa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Doces","ITEM":"Torta Sonho de Valsa - Grande","ACTIVE":"FALSO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Doces","ITEM":"Pudim de Caramelo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Frutas","ITEM":"Abacaxi","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Melão","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Mamão","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Manga","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Salada de Frutas","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Creme de Papaya","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Creme de Manga","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Tortas Geladas","ITEM":"Torta de Limão","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Tortas Geladas","ITEM":"Almendrado","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Tortas Geladas","ITEM":"Torta Alemã","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Tortas Geladas","ITEM":"Torta Holandesa","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Tortas Geladas","ITEM":"Profiteroles","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":24},
  {"GROUP":"Sorvetes","ITEM":"Tartufo","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Sorvetes","ITEM":"Taça (1 bola)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":10},
  {"GROUP":"Sorvetes","ITEM":"Taça (2 bolas)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sorvetes","ITEM":"Colegial","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Água e Refrigerantes","ITEM":"Água de Côco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Água Mineral sem Gás","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Água e Refrigerantes","ITEM":"Água Mineral com Gás","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Água e Refrigerantes","ITEM":"H2OH! Limão","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":9},
  {"GROUP":"Água e Refrigerantes","ITEM":"H2OH! Limoneto","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":9},
  {"GROUP":"Água e Refrigerantes","ITEM":"Coca-Cola Zero","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Fanta Laranja","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Fanta Uva","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Guaraná","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Coca-Cola","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Guaraná Zero","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Soda Limonada","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Soda Limonada Zero","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica Zero","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica Schweppes","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica Schweppes Diet","ACTIVE":"FALSO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica Schweppes Limão","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica Schweppes Limão Diet","ACTIVE":"FALSO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água e Refrigerantes","ITEM":"Tônica Indian Prata","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Água e Refrigerantes","ITEM":"Ginger Prata","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":9},
  {"GROUP":"Água e Refrigerantes","ITEM":"Soda","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":8},
  {"GROUP":"Drinks","ITEM":"Aperol Spritz","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Bloody Mary","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Gin Tônica","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Cuba-Libre","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Negroni","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Drinks","ITEM":"Sbagliato","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Whisky sauer","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Drinks","ITEM":"Caju Amigo","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":23},
  {"GROUP":"Drinks","ITEM":"Martini da casa","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Cervejas","ITEM":"Stella Artois (Longneck)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Cervejas","ITEM":"Stella Artois","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Cervejas","ITEM":"Heineken (Longneck)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Cervejas","ITEM":"Heineken","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Cervejas","ITEM":"Bohemia Pilsen","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":14},
  {"GROUP":"Cervejas","ITEM":"Malzbier (Longneck)","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":11},
  {"GROUP":"Cervejas","ITEM":"Original","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Cervejas","ITEM":"Sem Álcool (Longneck)","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":11},
  {"GROUP":"Cervejas","ITEM":"Serramalte","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Absolut","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Espirito de Minas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Sagatiba","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Sakê","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Salinas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Smirnoff","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Steinhager Becosa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Santo Grau","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Stolichnaya","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Cachaça","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Caipirinhas","ITEM":"Caipirosca de Rum","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Café e Chá","ITEM":"Café Expresso","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Café e Chá","ITEM":"Café Expresso com Sambuca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Café e Chá","ITEM":"Café Correto (com grappa)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Café e Chá","ITEM":"Café Macchiato","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Café e Chá","ITEM":"Chá ou Infusão","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Café e Chá","ITEM":"Chá Mate Leão","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":9,"PRICE_MENU":9},
  {"GROUP":"Café e Chá","ITEM":"Grape Tea Salton - Limão Siciliano","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":12},
  {"GROUP":"Café e Chá","ITEM":"Salton - Chá Preto com uva merlot e sabor frutas vermelhas","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Café e Chá","ITEM":"Salton - Chá Preto com uva moscato e sabor tangerina","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Café e Chá","ITEM":"Salton - Chá Verde com uva moscato e sabor limão siciliano e erva cidreira","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Café e Chá","ITEM":"Salton - Chá Branco com uva moscato e água de côco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Aperitivos","ITEM":"Campari","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Aperitivo da Casa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Cynar","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Aperitivos","ITEM":"Tequila José Cuervo Oro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Aperitivos","ITEM":"Gin Seagers","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Rum Bacardi Ouro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Rum Bacardi Prata","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Sakê Azuma","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Steinheger Becosa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Steinheger Schilichte","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Aperitivos","ITEM":"Underberg","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Gin Gordon's","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Brandy e Conhaques","ITEM":"Domecq","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Brandy e Conhaques","ITEM":"Fundador","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Brandy e Conhaques","ITEM":"Macieira Royal Brand","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Cachaças","ITEM":"Espírito de Minas - MG","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Cachaças","ITEM":"Sagatiba Prata - SP","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Cachaças","ITEM":"Salinas - MG","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Cachaças","ITEM":"Santo Grau - MG","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Cachaças","ITEM":"São Francisco","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":12},
  {"GROUP":"Digestivos","ITEM":"Grappa Giovane - Italiana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Digestivos","ITEM":"Grappa Invecchiata - Italiana","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Digestivos","ITEM":"Fernet Branca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Sucos","ITEM":"Suco de Abacaxi","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Abacaxi com hortelã","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Acerola","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Cajá","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Cajú","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Laranja","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Manga","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Maracujá","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Melancia","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Melão","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Sucos","ITEM":"Suco de Morango","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Sucos","ITEM":"Suco de Tomate","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":16},
  {"GROUP":"Sucos","ITEM":"Suco de Uva","ACTIVE":"FALSO","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Uva Integral Perini","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Sucos","ITEM":"Suco de Uva Integral Salton","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Sucos","ITEM":"Suco del Valle Uva (290ml)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Sucos","ITEM":"Suco del Valle Maracujá (290ml)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Sucos","ITEM":"Suco del Valle Laranja (250ml)","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Vodkas","ITEM":"Absolut","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Vodkas","ITEM":"Smirnoff","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Vodkas","ITEM":"Stolichnaya","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porto","ITEM":"Adriano Ramos Pinto","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Porto","ITEM":"Dom José","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Vermouth","ITEM":"Carpano Punt e Mes IT","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Vermouth","ITEM":"Vermouth Branco Doce","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Vermouth","ITEM":"Vermouth Branco Seco","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Vermouth","ITEM":"Vermouth Tinto","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Whiskies","ITEM":"Johnnie Walker Black Label","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Whiskies","ITEM":"Chivas 12 anos","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Whiskies","ITEM":"J. B.","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Whiskies","ITEM":"Jack Daniel's","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Whiskies","ITEM":"Johnnie Walker Red Label","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Amaro","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Amaretto d'Orso","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Amarula","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Baileys","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Cointreau","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Licores","ITEM":"Drambuie","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Frangélico","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Licor 43","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Licor de Cassis Jean Dijon","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Limoncello","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Mandarineto Isolabella","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Maraschino","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Peach Tree","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Sambuca IT","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Strega IT","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Outros","ITEM":"Embalagem","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":0,"PRICE_MENU":3},
  {"GROUP":"Empório","ITEM":"Ragu di Ossobuco 520g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Empório","ITEM":"Ragu di Ossobuco 220g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24,"PRICE_MENU":24},
  {"GROUP":"Empório","ITEM":"Ragu alla Bolognese 520g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Empório","ITEM":"Ragu alla Bolognese 220g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24,"PRICE_MENU":24},
  {"GROUP":"Empório","ITEM":"Sugo all'Arrabiata 310g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Empório","ITEM":"Molho Siciliano 220g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24,"PRICE_MENU":24},
  {"GROUP":"Empório","ITEM":"Molho Siciliano 520g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Empório","ITEM":"Caldo de Galinha Caipira 300ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":14,"PRICE_MENU":14},
  {"GROUP":"Empório","ITEM":"Caldo de Carne 300ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":14,"PRICE_MENU":14},
  {"GROUP":"Empório","ITEM":"Caldo de Galinha Caipira 700ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":21,"PRICE_MENU":21},
  {"GROUP":"Empório","ITEM":"Caldo de Carne 700ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":21,"PRICE_MENU":21},
  {"GROUP":"Empório","ITEM":"Vinagre It Balsamico de Modena IGP 500ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Empório","ITEM":"Condimento Suco de Limão Siciliano 200ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":6,"PRICE_MENU":6},
  {"GROUP":"Empório","ITEM":"Molho It Tomate Pelati 2.5kg","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":37,"PRICE_MENU":37},
  {"GROUP":"Empório","ITEM":"Massa It Fettuccine - Pasta di Sardegna 500g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":11,"PRICE_MENU":11},
  {"GROUP":"Empório","ITEM":"Arroz It Arbóreo Riso di Sardegna 1kg","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":26,"PRICE_MENU":26},
  {"GROUP":"Empório","ITEM":"Massa It Penne Rigate Pasta di Sardegna 500g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":11,"PRICE_MENU":11},
  {"GROUP":"Empório","ITEM":"Massa It Spaghetti n. 305 Pasta di Sardegna 500g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":11,"PRICE_MENU":11},
  {"GROUP":"Empório","ITEM":"Massa It Divella Rigatoni 500g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Empório","ITEM":"Geléia Troppo de Framboesa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24.5,"PRICE_MENU":24.5},
  {"GROUP":"Empório","ITEM":"Geléia Troppo de Maçã com Canela","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24.5,"PRICE_MENU":24.5},
  {"GROUP":"Empório","ITEM":"Relish de Cebola Roxa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24.5,"PRICE_MENU":24.5},
  {"GROUP":"Empório","ITEM":"Relish de Tomate com Funcho","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24.5,"PRICE_MENU":24.5},
  {"GROUP":"Empório","ITEM":"Queijo Tipo Grana Padano","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":17.5,"PRICE_MENU":17.5},
  {"GROUP":"Empório","ITEM":"Queijo Caccio Cavalo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":37,"PRICE_MENU":37},
  {"GROUP":"Empório","ITEM":"Kit de Queijo. Faca e Tábula","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Empório","ITEM":"Burrata Búfalo Dourado","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":0},
  {"GROUP":"Empório","ITEM":"Burrata Búfalo Dourado ao Tartufo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":23,"PRICE_MENU":0},
  {"GROUP":"Empório","ITEM":"Azeite O-live","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":32,"PRICE_MENU":32},
  {"GROUP":"Empório","ITEM":"Ragu di Mare 220g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Mercato","ITEM":"Polvilho Azedo Canastra","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":18,"PRICE_MENU":18},
  {"GROUP":"Mercato","ITEM":"Café Canastra","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":22,"PRICE_MENU":22},
  {"GROUP":"Mercato","ITEM":"Maturador de Queijo Canastra","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":250,"PRICE_MENU":250},
  {"GROUP":"Mercato","ITEM":"Goiabada","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":17,"PRICE_MENU":17},
  {"GROUP":"Mercato","ITEM":"Doce de Abóbora","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":29,"PRICE_MENU":29},
  {"GROUP":"Mercato","ITEM":"Azeitona Verde Recheada 195g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Azeito Verde Raiolita 180g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":7,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Tomate Pelado Italiano 400g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8.5,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Vinagre de Vinho Tinto Raiola 500ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":16,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Tremoço Raiola 200g","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":12,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Suco de Tomate Raiola 500ml","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":13,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Mini Chocotone com M&Ms","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Arroz Arbóreo La Pastina","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":25,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Crostini Sal Marinho e Alecrim","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Crostini Parmesão e Pecorino","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Tarallo Mediterrâneo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Fundo de Alcachofra","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":22,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Aspargo Verde","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":31,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Bruscheta de Alcachofra","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":24,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Molho de Alcachofra","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":27,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Molho Putanesca","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":27,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Alcachofra na Brasa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":27,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Chá Carmencita de Gengibre e Mel","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":18,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Carpaccio di Tartufo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":132,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Crema di Carciofi e Tartufo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":57,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Funghi Porcini Sechi","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":50,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Salsa di Olive e Tartufo","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":60,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Mix Vegetais na Brasa","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":27,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Tortellini 3 Queijos","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":20,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Bucatini Divella","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":8,"PRICE_MENU":0},
  {"GROUP":"Mercato","ITEM":"Pomodori Pelati Organico","ACTIVE":"VERDADEIRO","PRICE_DELIVERY":10.5,"PRICE_MENU":0}
];

export default dadosDeliveryItems;