const dadosDeliveryItems = [
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Coca-Cola (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Coca-Cola Zero (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Fanta Uva (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Fanta Laranja (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Soda Limonada (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Soda Limonada Zero (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica Zero (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica schweppes (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Schweppes Zero (Lata)","ACTIVE":"FALSE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica schweppes Limão (Lata)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Schweppes Limão Zero (Lata)","ACTIVE":"FALSE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Água com Gás","ACTIVE":"TRUE","PRICE_MENU":"7,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Água sem Gás","ACTIVE":"TRUE","PRICE_MENU":"7,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"H2OH! Limão","ACTIVE":"TRUE","PRICE_MENU":"9,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"H2OH! Limoneto","ACTIVE":"TRUE","PRICE_MENU":"9,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Água de Côco","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Abacaxi","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Abacaxi com Hortelã","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Acerola","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Cajá","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Cajú","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Laranja","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Manga","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Maracujá","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Melancia","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Melão","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de morango","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Tomate","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Uva","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Uva Integral Perini","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Couvert","ITEM":"Cesta de Pães","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Couvert","ITEM":"Pão com Manteiga","ACTIVE":"TRUE","PRICE_MENU":"13,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Couvert","ITEM":"Completo de 2ª a 6ª Almoço","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Couvert","ITEM":"Completo de FDS, Feriado e Jantar","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Antipasto","ITEM":"Antipasto (2 cestas/1 filão)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Antipasto","ITEM":"Antipasto Médio (1 cesta/meio filão)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Antipasto","ITEM":"Abobrinha (150g)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Antipasto","ITEM":"Aliche Italiano (90g di salerno)","ACTIVE":"FALSE","PRICE_MENU":"70,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Antipasto","ITEM":"Azeitonas Azapa (200g Raiola)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Antipasto","ITEM":"Berinjela Vinagrete (1 banda)","ACTIVE":"TRUE","PRICE_MENU":"18,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Antipasto","ITEM":"Berinjela Recheada (1 banda)","ACTIVE":"TRUE","PRICE_MENU":"28,00","PRICE_DELIVERY":"24,00"},
  {"GROUP":"Antipasto","ITEM":"Calabresa","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Antipasto","ITEM":"Pasta Pimentão Verde e Ricota (200g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Antipasto","ITEM":"Pimentão Rosso (100g)","ACTIVE":"TRUE","PRICE_MENU":"28,00","PRICE_DELIVERY":"22,00"},
  {"GROUP":"Antipasto","ITEM":"Provolone (200g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Antipasto","ITEM":"Salada napolitana (200g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Antipasto","ITEM":"Salame (100g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Antipasto","ITEM":"Sardela (200g)","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Antipasto","ITEM":"Caponata (200g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Antipasto","ITEM":"Tomate Seco (200g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Salada","ITEM":"Completa Tradicional","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Completa Individual","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Carpaccio","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Palmito e Brócolis","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Tomate","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Tomate e Palmito","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Salada","ITEM":"Brócolis","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Palmito","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Salada","ITEM":"Verdes","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Infantil","ITEM":"Espaguete ao Sugo c/ Almondega","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Infantil","ITEM":"Espaguete com Escalopine","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Infantil","ITEM":"Escalopine, Arroz e Fritas","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Sopas","ITEM":"Canja","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Sopas","ITEM":"Cap Brodo Qjo Presunto","ACTIVE":"TRUE","PRICE_MENU":"85,00","PRICE_DELIVERY":"85,00"},
  {"GROUP":"Frango","ITEM":"Passarinho 1/1","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Frango","ITEM":"passarinho 1/2","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Frango","ITEM":"1/2 desossado Grelhado","ACTIVE":"TRUE","PRICE_MENU":"44,00","PRICE_DELIVERY":"44,00"},
  {"GROUP":"Frango","ITEM":"1/2 desossado + Creme de Milho","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Frango","ITEM":"1/2 desossado + Purê e Champignon","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Frango","ITEM":"1/2 desossado a Cubana","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Frango","ITEM":"1/2 desossado + Brócolis","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Frango","ITEM":"Frango à Parmigiana A/F","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Frango","ITEM":"Frango à Parmigiana A/F (ind)","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Carne","ITEM":"Ropertone","ACTIVE":"TRUE","PRICE_MENU":"85,00","PRICE_DELIVERY":"85,00"},
  {"GROUP":"Carne","ITEM":"Mini Ropertone c/ arroz","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Carne","ITEM":"Brachola (1 Unidade)","ACTIVE":"TRUE","PRICE_MENU":"38,00","PRICE_DELIVERY":"38,00"},
  {"GROUP":"Carne","ITEM":"Almondegas (6 Unidades)","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Cabrito","ITEM":"Perna Traseira","ACTIVE":"TRUE","PRICE_MENU":"260,00","PRICE_DELIVERY":"260,00"},
  {"GROUP":"Cabrito","ITEM":"à Caçadora","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Cabrito","ITEM":"à Caçadora (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Cabrito","ITEM":"ao Forno","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Cabrito","ITEM":"ao Forno (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Risoto","ITEM":"de Frango","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Risoto","ITEM":"de Camarão","ACTIVE":"TRUE","PRICE_MENU":"150,00","PRICE_DELIVERY":"150,00"},
  {"GROUP":"Risoto","ITEM":"de Frutos do Mar","ACTIVE":"TRUE","PRICE_MENU":"120,00","PRICE_DELIVERY":"120,00"},
  {"GROUP":"Peixe","ITEM":"Pescada c/ Purê e Brócolis p/2","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Peixe","ITEM":"Pescada c/ Purê e Brócolis p/1","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Peixe","ITEM":"Pescada c/ M de Camarão p/2","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Peixe","ITEM":"Pescada c/ M de Camarão p/1","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Outros","ITEM":"Beringela Parm c/ Arroz","ACTIVE":"TRUE","PRICE_MENU":"88,00","PRICE_DELIVERY":"88,00"},
  {"GROUP":"Porções","ITEM":"Brócolis Alho e Óleo","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Porções","ITEM":"Polenta Frita","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Porções","ITEM":"Arroz","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Porções","ITEM":"Arroz à Grega","ACTIVE":"TRUE","PRICE_MENU":"34,00","PRICE_DELIVERY":"34,00"},
  {"GROUP":"Porções","ITEM":"Batata Frita","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Porções","ITEM":"Purê de Batatas","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Porções","ITEM":"Creme de Milho","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Porções","ITEM":"Bananas à Milanesa (2 Unidades)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Porções","ITEM":"Brócolis com Catupiry","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Doces","ITEM":"Pastiera de Grão","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Doces","ITEM":"Petit Gateau","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Doces","ITEM":"Tiramisu","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Doces","ITEM":"Pudim de Caramelo","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Sorvetes","ITEM":"Tartufo","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Sorvetes","ITEM":"Taça (1 bola)","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Sorvetes","ITEM":"Colegial","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Tortas Geladas","ITEM":"de Limão","ACTIVE":"FALSE","PRICE_MENU":"20,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Tortas Geladas","ITEM":"Almendrado","ACTIVE":"FALSE","PRICE_MENU":"17,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Tortas Geladas","ITEM":"Alemã","ACTIVE":"FALSE","PRICE_MENU":"17,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Tortas Geladas","ITEM":"Holandesa","ACTIVE":"FALSE","PRICE_MENU":"17,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Tortas Geladas","ITEM":"Profiteroles","ACTIVE":"FALSE","PRICE_MENU":"24,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Abacaxi","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Melão","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Mamão","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Manga","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Salada de Frutas","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Creme de Papaya","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frutas","ITEM":"Creme de Manga","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Molhos","ITEM":"ao Sugo","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"à Napolitana","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"ao Pesto","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"à Genovesa","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"à Putanesca","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"aos 4Q","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"à Parisiense","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"à Romanesca","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"Rosé","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"à Carbonara Americana","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"com Aliche Italiano","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Molhos","ITEM":"ao Vongolis","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Molhos","ITEM":"Alho e Óleo","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"à Bolonhesa","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"com Brócolis A&O","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"à calabresa","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"Gratinado","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"com Funghi Seco","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"à Michelangelo","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"à Etrusca","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Simples (400g)","ACTIVE":"TRUE","PRICE_MENU":"85,00","PRICE_DELIVERY":"85,00"},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado (Médio 200g)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Couvert","ITEM":"Couvert Comp com cesta de pães","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa (400g s/ Acomp)","ACTIVE":"TRUE","PRICE_MENU":"120,00","PRICE_DELIVERY":"120,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa A/F  (400g)","ACTIVE":"TRUE","PRICE_MENU":"140,00","PRICE_DELIVERY":"140,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa A/F (100g ind)","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Alho e Óleo c/ Arroz (400g)","ACTIVE":"TRUE","PRICE_MENU":"130,00","PRICE_DELIVERY":"130,00"},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado com Fritas (400g)","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"110,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana (400g s/ Acomp)","ACTIVE":"TRUE","PRICE_MENU":"130,00","PRICE_DELIVERY":"130,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana A/F (400g)","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana A/F (100g ind)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Roperto (400g)","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Pizzaiolo com Arroz (400g)","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Cubana com Arroz (400g)","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Cordonbleu (400g)","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Filé Mignon","ITEM":"d'Alê A/F (400g)","ACTIVE":"TRUE","PRICE_MENU":"150,00","PRICE_DELIVERY":"150,00"},
  {"GROUP":"Filé Mignon","ITEM":"d'Alê A/F (200g individual)","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (400g)","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (100g ind)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Salada","ITEM":"Mista Grande","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Antipasto","ITEM":"Berinjela all'Inferno (200g)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Salada","ITEM":"Escarola, Salsão, Bacon & Alho","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Sopas","ITEM":"Minestrone de legumes","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Massas","ITEM":"Espaguete","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Massas","ITEM":"Penne","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Massas","ITEM":"Rigatone","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Massas","ITEM":"Agnolotti","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Canelone V.","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Canelone Branco","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Lasanha","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Massas","ITEM":"Richitelli","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Massas","ITEM":"Fetuccine branco","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Massas","ITEM":"Fusilli","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Massas","ITEM":"Ravioli de Ricota","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Ravioli de Carne","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Ravioli de Búfala","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Gnocchi de Batata","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Massas","ITEM":"Rondelli","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Café & Chá","ITEM":"Café Macchiato","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Sopas","ITEM":"Minestrone de legumes (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Sopas","ITEM":"Cap Brodo Qjo Pres (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Sopas","ITEM":"Canja (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Massas","ITEM":"Cappelletti","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Fetuccine verde","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Vinho","ITEM":"Baron d'Arignac 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"87,00","PRICE_DELIVERY":"56,00"},
  {"GROUP":"Vinho","ITEM":"Valpolicella Bolla 750ml","ACTIVE":"TRUE","PRICE_MENU":"140,00","PRICE_DELIVERY":"91,00"},
  {"GROUP":"Vinho","ITEM":"Calamares 750ml Rosé","ACTIVE":"TRUE","PRICE_MENU":"95,00","PRICE_DELIVERY":"62,00"},
  {"GROUP":"Vinho","ITEM":"Calamares 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"95,00","PRICE_DELIVERY":"62,00"},
  {"GROUP":"Vinho","ITEM":"Casal Garcia 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Vinho","ITEM":"Casal Garcia 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Vinho","ITEM":"Concha y Toro - Reservado 750ml","ACTIVE":"TRUE","PRICE_MENU":"54,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Vinho","ITEM":"Corvo Rosso 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"121,00","PRICE_DELIVERY":"79,00"},
  {"GROUP":"Vinho","ITEM":"Corvo Rosso 375ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"73,00","PRICE_DELIVERY":"47,00"},
  {"GROUP":"Vinho","ITEM":"Corvo Bianco 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"103,00","PRICE_DELIVERY":"67,00"},
  {"GROUP":"Vinho","ITEM":"Dão Grao Vasco 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"98,00","PRICE_DELIVERY":"64,00"},
  {"GROUP":"Vinho","ITEM":"Finca Flichman 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"96,00","PRICE_DELIVERY":"63,00"},
  {"GROUP":"Vinho","ITEM":"Lambrusco Caravaggio 750ml","ACTIVE":"TRUE","PRICE_MENU":"56,00","PRICE_DELIVERY":"36,00"},
  {"GROUP":"Vinho","ITEM":"Macul Don Luis 750ml","ACTIVE":"TRUE","PRICE_MENU":"107,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Vinho","ITEM":"Mateus Rosé 750ml Rosé","ACTIVE":"TRUE","PRICE_MENU":"105,00","PRICE_DELIVERY":"68,00"},
  {"GROUP":"Vinho","ITEM":"Montepulciano Nova Corte 750ml","ACTIVE":"TRUE","PRICE_MENU":"149,00","PRICE_DELIVERY":"97,00"},
  {"GROUP":"Vinho","ITEM":"Periquita 375ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"66,00","PRICE_DELIVERY":"43,00"},
  {"GROUP":"Vinho","ITEM":"Periquita 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"71,00"},
  {"GROUP":"Vinho","ITEM":"Chianti Ruffino 750ml","ACTIVE":"TRUE","PRICE_MENU":"159,00","PRICE_DELIVERY":"104,00"},
  {"GROUP":"Vinho","ITEM":"Santa Helena 375ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"36,00","PRICE_DELIVERY":"24,00"},
  {"GROUP":"Vinho","ITEM":"Santa Helena 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"39,00"},
  {"GROUP":"Vinho","ITEM":"Santa Carolina 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"62,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Vinho","ITEM":"Côtes du Rhône 750ml","ACTIVE":"TRUE","PRICE_MENU":"224,00","PRICE_DELIVERY":"160,00"},
  {"GROUP":"Vinho","ITEM":"Casillero del Diablo 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"89,00","PRICE_DELIVERY":"58,00"},
  {"GROUP":"Vinho","ITEM":"Gato Negro 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"71,00","PRICE_DELIVERY":"46,00"},
  {"GROUP":"Vinho","ITEM":"Marques de Riscal 750ml","ACTIVE":"TRUE","PRICE_MENU":"424,00","PRICE_DELIVERY":"424,00"},
  {"GROUP":"Vinho","ITEM":"Tarapaca Cosecha 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"47,00"},
  {"GROUP":"Vinho","ITEM":"Leon Tarapaca 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"97,00","PRICE_DELIVERY":"63,00"},
  {"GROUP":"Vinho","ITEM":"Benjamim Nieto 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"49,00"},
  {"GROUP":"Vinho","ITEM":"Alamos - 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_MENU":"169,00","PRICE_DELIVERY":"121,00"},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 375ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"111,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Vinho","ITEM":"Finca La Daniela 750ml Malbec","ACTIVE":"TRUE","PRICE_MENU":"112,00","PRICE_DELIVERY":"73,00"},
  {"GROUP":"Vinho","ITEM":"Cava Negra 750ml Malbec","ACTIVE":"TRUE","PRICE_MENU":"83,00","PRICE_DELIVERY":"54,00"},
  {"GROUP":"Vinho","ITEM":"Sangiovese Bonacchi 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"152,00","PRICE_DELIVERY":"108,00"},
  {"GROUP":"Vinho","ITEM":"Uxmal 750ml Malbec-Syrah","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"104,00"},
  {"GROUP":"Vinho","ITEM":"Alamos - 375ml Tinto Malbec","ACTIVE":"TRUE","PRICE_MENU":"135,00","PRICE_DELIVERY":"88,00"},
  {"GROUP":"Vinho","ITEM":"Catena Malbec 375ml Malbec","ACTIVE":"TRUE","PRICE_MENU":"169,00","PRICE_DELIVERY":"121,00"},
  {"GROUP":"Vinho","ITEM":"Chianti Gentilesco 750ml","ACTIVE":"TRUE","PRICE_MENU":"200,00","PRICE_DELIVERY":"143,00"},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Merlot","ACTIVE":"TRUE","PRICE_MENU":"41,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Vinho","ITEM":"Barbera d'Asti Batasiolo 750ml","ACTIVE":"TRUE","PRICE_MENU":"156,00","PRICE_DELIVERY":"111,00"},
  {"GROUP":"Vinho","ITEM":"Brunello di Montalcino 750ml","ACTIVE":"TRUE","PRICE_MENU":"502,00","PRICE_DELIVERY":"502,00"},
  {"GROUP":"Vinho","ITEM":"Casas  del Toqui 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"78,00","PRICE_DELIVERY":"51,00"},
  {"GROUP":"Vinho","ITEM":"Saccheto 750ml Tinto Merlot","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"106,00"},
  {"GROUP":"Vinho","ITEM":"Chianti Ponte Vecchio Torciglione 3L","ACTIVE":"TRUE","PRICE_MENU":"541,00","PRICE_DELIVERY":"541,00"},
  {"GROUP":"Vinho","ITEM":"Barolo 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"374,00","PRICE_DELIVERY":"330,00"},
  {"GROUP":"Vinho","ITEM":"Amarone della Valpolicella 750ml","ACTIVE":"TRUE","PRICE_MENU":"514,00","PRICE_DELIVERY":"514,00"},
  {"GROUP":"Vinho","ITEM":"Santa Alvara 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"137,00","PRICE_DELIVERY":"89,00"},
  {"GROUP":"Vinho","ITEM":"DV Catena 750ml Cabernet-Malbec","ACTIVE":"TRUE","PRICE_MENU":"299,00","PRICE_DELIVERY":"236,00"},
  {"GROUP":"Vinho","ITEM":"Corvo Bianco 375ml Branco","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Prosecco Sperone 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"165,00","PRICE_DELIVERY":"118,00"},
  {"GROUP":"Vinho","ITEM":"Pinot Grigio 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"160,00","PRICE_DELIVERY":"114,00"},
  {"GROUP":"Vinho","ITEM":"Angelica Zapata 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"330,00","PRICE_DELIVERY":"291,00"},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"152,00","PRICE_DELIVERY":"108,00"},
  {"GROUP":"Vinho","ITEM":"Catena Malbec 750ml Malbec","ACTIVE":"TRUE","PRICE_MENU":"261,00","PRICE_DELIVERY":"206,00"},
  {"GROUP":"Vinho","ITEM":"Chianti Gentilesco 375ml","ACTIVE":"TRUE","PRICE_MENU":"157,00","PRICE_DELIVERY":"102,00"},
  {"GROUP":"Vinho","ITEM":"Valpolicella Bolla 375ml","ACTIVE":"TRUE","PRICE_MENU":"108,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Vinho","ITEM":"Salton Brut 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"64,00","PRICE_DELIVERY":"42,00"},
  {"GROUP":"Vinho","ITEM":"Alma Negra 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"276,00","PRICE_DELIVERY":"218,00"},
  {"GROUP":"Vinho","ITEM":"Valdemoreda 750ml Tempranillo","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"102,00"},
  {"GROUP":"Vinho","ITEM":"Copa Real Oro Tempranillo 750ml","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"94,00"},
  {"GROUP":"Vinho","ITEM":"IGT Folino Capito Vênezie 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"97,00"},
  {"GROUP":"Vinho","ITEM":"IGT Folino Capito 750ml Merlot\nerlot","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"106,00"},
  {"GROUP":"Vinho","ITEM":"IGT  Primitivo Puglia 750ml","ACTIVE":"TRUE","PRICE_MENU":"168,00","PRICE_DELIVERY":"120,00"},
  {"GROUP":"Vinho","ITEM":"D´Alamel 750ml Merlot","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"127,00"},
  {"GROUP":"Vinho","ITEM":"D`Alamel 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"127,00"},
  {"GROUP":"Vinho","ITEM":"Carmen Premier 750ml Pinot Noir","ACTIVE":"TRUE","PRICE_MENU":"212,00","PRICE_DELIVERY":"151,00"},
  {"GROUP":"Vinho","ITEM":"Mapema 750ml","ACTIVE":"TRUE","PRICE_MENU":"220,00","PRICE_DELIVERY":"157,00"},
  {"GROUP":"Vinho","ITEM":"Santa Helena 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"39,00"},
  {"GROUP":"Vinho","ITEM":"Salton Brut 375ml Branco","ACTIVE":"TRUE","PRICE_MENU":"52,00","PRICE_DELIVERY":"34,00"},
  {"GROUP":"Vinho","ITEM":"Bis 750ml","ACTIVE":"TRUE","PRICE_MENU":"87,00","PRICE_DELIVERY":"57,00"},
  {"GROUP":"Vinho","ITEM":"Vallontano 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"89,00"},
  {"GROUP":"Vinho","ITEM":"Santo Cristo Amphora 750ml","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"98,00"},
  {"GROUP":"Vinho","ITEM":"Rosso Piceno (orgânico) 750ml","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"127,00"},
  {"GROUP":"Vinho","ITEM":"Posada Vieja 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Vinho","ITEM":"Nero D´Avola Bonacchi 750ml","ACTIVE":"TRUE","PRICE_MENU":"161,00","PRICE_DELIVERY":"115,00"},
  {"GROUP":"Vinho","ITEM":"Santa Alvara 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"137,00","PRICE_DELIVERY":"89,00"},
  {"GROUP":"Vinho","ITEM":"Marius Rouge 750ml","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"114,00"},
  {"GROUP":"Vinho","ITEM":"Estiba 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"102,00"},
  {"GROUP":"Vinho","ITEM":"Estiba 750ml Malbec","ACTIVE":"TRUE","PRICE_MENU":"157,00","PRICE_DELIVERY":"102,00"},
  {"GROUP":"Vinho","ITEM":"D´Alamel 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"127,00"},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"152,00","PRICE_DELIVERY":"108,00"},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Merlot","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"108,00"},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Syrah","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"108,00"},
  {"GROUP":"Vinho","ITEM":"Alamos Seleccion - 750ml Pinot Noir","ACTIVE":"TRUE","PRICE_MENU":"215,00","PRICE_DELIVERY":"170,00"},
  {"GROUP":"Vinho","ITEM":"Casillero del Diablo 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"89,00","PRICE_DELIVERY":"58,00"},
  {"GROUP":"Vinho","ITEM":"Gato Negro 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"71,00","PRICE_DELIVERY":"46,00"},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"41,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Tannat","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Vinho","ITEM":"Salton Prosecco Brut 750ml Branco","ACTIVE":"TRUE","PRICE_MENU":"64,00","PRICE_DELIVERY":"42,00"},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Malbec","ACTIVE":"FALSE","PRICE_MENU":"0,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Pinot Noir","ACTIVE":"TRUE","PRICE_MENU":"64,00","PRICE_DELIVERY":"42,00"},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"64,00","PRICE_DELIVERY":"42,00"},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Merlot","ACTIVE":"TRUE","PRICE_MENU":"64,00","PRICE_DELIVERY":"42,00"},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Chardonay","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"42,00"},
  {"GROUP":"Vinho","ITEM":"Saccheto 750ml Tinto Cab Sauv","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"106,00"},
  {"GROUP":"Vinho","ITEM":"Valpolicella Ripasso 750ml","ACTIVE":"TRUE","PRICE_MENU":"302,00","PRICE_DELIVERY":"267,00"},
  {"GROUP":"Vinho","ITEM":"Bayanegra 750ml Tinto Tempranillo","ACTIVE":"TRUE","PRICE_MENU":"144,00","PRICE_DELIVERY":"94,00"},
  {"GROUP":"Vinho","ITEM":"Casas  del Toqui 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"78,00","PRICE_DELIVERY":"51,00"},
  {"GROUP":"Vinho","ITEM":"Lagoalva 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"115,00"},
  {"GROUP":"Vinho","ITEM":"La Camioneta 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"93,00"},
  {"GROUP":"Vinho","ITEM":"Caldirola Corte Antica 750ml","ACTIVE":"TRUE","PRICE_MENU":"0,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Vinho","ITEM":"Bardolino Classico DOC 750ml","ACTIVE":"TRUE","PRICE_MENU":"183,00","PRICE_DELIVERY":"130,00"},
  {"GROUP":"Vinho","ITEM":"Dolcetto d'Alba 750ml Tinto","ACTIVE":"TRUE","PRICE_MENU":"166,00","PRICE_DELIVERY":"118,00"},
  {"GROUP":"Vinho","ITEM":"Montes Alpha 750ml Tempranillo","ACTIVE":"TRUE","PRICE_MENU":"286,00","PRICE_DELIVERY":"252,00"},
  {"GROUP":"Vinho","ITEM":"Baron Phillippe 750ml Cab Sauvignon","ACTIVE":"TRUE","PRICE_MENU":"92,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Café & Chá","ITEM":"Café Expresso","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Café & Chá","ITEM":"Café Correto (com grappa)","ACTIVE":"TRUE","PRICE_MENU":"12,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Café & Chá","ITEM":"Café com Sambuca","ACTIVE":"TRUE","PRICE_MENU":"12,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Café & Chá","ITEM":"Chá ou Infusão","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Digestivos","ITEM":"Fernet Branca","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Absolut","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Esp de Minas","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Sagatiba","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Sakê","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Salinas","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Smirnoff","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Steinhaeger Becosa","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Santo Grau","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Stolichnaya","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Caipirinhas","ITEM":"Caipirosca de Rum","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Cervejas","ITEM":"Heineken (Longneck)","ACTIVE":"TRUE","PRICE_MENU":"12,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Cachaças","ITEM":"Espirito de Minas - MG","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Cachaças","ITEM":"Sagatiba Prata - SP","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Cachaças","ITEM":"Salinas - MG","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Cachaças","ITEM":"Santo Grau - MG","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Cervejas","ITEM":"Stella Artois (Longneck)","ACTIVE":"TRUE","PRICE_MENU":"12,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Licores","ITEM":"Amaretto d'Orso","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Amarula","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Baileys","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Cointreau","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Licores","ITEM":"Drambui","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Frangelico","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Licor 43","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Licor de Cassis Jean Dijon","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Limoncello","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Mandarineto Isolabella","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Maraschino","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Peach Tree","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Sambuca IT","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Strega IT","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Licores","ITEM":"Amaro","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Porto","ITEM":"Adriano Ramos Pinto","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Porto","ITEM":"Dom José","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Vodkas","ITEM":"Absolut","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Vodkas","ITEM":"Smirnoff","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Vodkas","ITEM":"Stolichnaya","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Vermouth","ITEM":"Carpano Punt e Mes IT","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Vermouth","ITEM":"Branco Doce","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Vermouth","ITEM":"Branco Seco","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Vermouth","ITEM":"Tinto","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Whikies","ITEM":"Johnnie Walker Black Label","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Whikies","ITEM":"Johnnie Walker Red Label","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Whikies","ITEM":"Chivas 12 anos","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Whikies","ITEM":"J. B.","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Whikies","ITEM":"Jack Daniels","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Drinks","ITEM":"Aperol Spritz","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Drinks","ITEM":"Bloody mary","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Drinks","ITEM":"Gin Tônica","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Drinks","ITEM":"Cuba-Libre","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Drinks","ITEM":"Negroni","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Drinks","ITEM":"Sbagliato","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Brandy e Conhaques","ITEM":"Macieira Royal Brand","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Brandy e Conhaques","ITEM":"Fundador","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Brandy e Conhaques","ITEM":"Domecq","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Digestivos","ITEM":"Grappa Giovane - IT","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Aperitivos","ITEM":"Campari","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Cynar","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Aperitivos","ITEM":"Tequila José Cuervo Oro","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Aperitivos","ITEM":"Gin Seagers","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Rum bacardi Ouro","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Rum Bacardi Prata","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Sakê Azuma","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Steinhaeger Becosa","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Steinhäger Schilichte","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Aperitivos","ITEM":"Underberg","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Aperitivos","ITEM":"Gin Gordon's","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Digestivos","ITEM":"Grappa Invecchiata - IT","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa (meio 200g s/ Acomp)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana (médio 200g s/ Acomp)","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado com fritas (200g Ind)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Filé Mignon","ITEM":"Escalope à Vienense (400g)","ACTIVE":"TRUE","PRICE_MENU":"150,00","PRICE_DELIVERY":"150,00"},
  {"GROUP":"Filé Mignon","ITEM":"Escalope à Vienense (200g Ind)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas Especiais","ITEM":"Espaguete Integral (ind)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas Especiais","ITEM":"Penne sem Glúten (ind)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Espaguete (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Massas","ITEM":"Penne (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Massas","ITEM":"Rigatone (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Massas","ITEM":"Agnolotti (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Canelloni verde (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Canelloni Branco (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Lasanha (individual)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Massas","ITEM":"Richitelli (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Massas","ITEM":"Fetuccine Branco (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Massas","ITEM":"Fetuccine Verde (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Massas","ITEM":"Fusilli (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Massas","ITEM":"Ravioli de Ricota (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Ravioli de Carne (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Ravioli de Búfala (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Gnocchi de Batata (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Massas","ITEM":"Rondelli (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Cappelletti (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Doces","ITEM":"Panna Cotta","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Sugestões","ITEM":"Agnolotti Gratinato","ACTIVE":"TRUE","PRICE_MENU":"105,00","PRICE_DELIVERY":"105,00"},
  {"GROUP":"Sugestões","ITEM":"Canelone V. ao Forno","ACTIVE":"TRUE","PRICE_MENU":"105,00","PRICE_DELIVERY":"105,00"},
  {"GROUP":"Sugestões","ITEM":"Cappelletti à Romanesca","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"110,00"},
  {"GROUP":"Sugestões","ITEM":"Fusili à Calabresa","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Sugestões","ITEM":"Lasanha à Bolonhesa","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Sugestões","ITEM":"Ravioli de Búf à Nap","ACTIVE":"TRUE","PRICE_MENU":"95,00","PRICE_DELIVERY":"95,00"},
  {"GROUP":"Sugestões","ITEM":"Richitelle salsa Rose","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Sugestões","ITEM":"Rondelle aos 4Q","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"110,00"},
  {"GROUP":"Sugestões","ITEM":"Fettuccine ao Pesto","ACTIVE":"TRUE","PRICE_MENU":"95,00","PRICE_DELIVERY":"95,00"},
  {"GROUP":"Sugestões","ITEM":"Espaguete c/ Almondegas","ACTIVE":"TRUE","PRICE_MENU":"105,00","PRICE_DELIVERY":"105,00"},
  {"GROUP":"Sugestões","ITEM":"Penne à Putanesca","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Sugestões","ITEM":"Rigatone à Genovesa","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Sugestões","ITEM":"Gnocchi à Michelangelo","ACTIVE":"TRUE","PRICE_MENU":"105,00","PRICE_DELIVERY":"105,00"},
  {"GROUP":"Sugestões","ITEM":"Agnolotti Gratinato (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Sugestões","ITEM":"Canelone V. ao Forno (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Sugestões","ITEM":"Cappelletti à Romanesca (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Sugestões","ITEM":"Fusili à Calabresa (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Sugestões","ITEM":"Lasanha à Bolonhesa (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Sugestões","ITEM":"Ravioli de Búf à Nap (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Sugestões","ITEM":"Richitelle Salsa Rose (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Sugestões","ITEM":"Rondelle aos 4Q (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"70,00","PRICE_DELIVERY":"70,00"},
  {"GROUP":"Sugestões","ITEM":"Fettuccine ao Pesto (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"55,00","PRICE_DELIVERY":"55,00"},
  {"GROUP":"Sugestões","ITEM":"Espaguete c/ Almondegas (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Sugestões","ITEM":"Penne à Putanesca (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Sugestões","ITEM":"Rigatone à Genovesa (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Sugestões","ITEM":"Gnocchi à Michelangelo (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Massas","ITEM":"Agnolotti V. Abób","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Massas","ITEM":"Agnolotti V. Abób (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Sugestões","ITEM":"Agnolotti V. Abób Rose","ACTIVE":"TRUE","PRICE_MENU":"105,00","PRICE_DELIVERY":"105,00"},
  {"GROUP":"Sugestões","ITEM":"Agnolotti V. Abób Rose (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Couvert","ITEM":"Filão de pão","ACTIVE":"TRUE","PRICE_MENU":"13,00","PRICE_DELIVERY":"13,00"},
  {"GROUP":"Couvert","ITEM":"Meio filão de pão","ACTIVE":"TRUE","PRICE_MENU":"7,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Salada","ITEM":"Tomate e palmito (média)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Salada","ITEM":"Mista Média","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Salada","ITEM":"Escarola, Salsão, Bacon & Alho (Média)","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"ao forno","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Molhos","ITEM":"ao Sugo (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Molhos","ITEM":"à Napolitana (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Molhos","ITEM":"ao Pesto (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"à Genovesa (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"à Putanesca (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"aos 4Q (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"à Parisiense (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"à Romanesca (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"Rosé (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"à Carbonara Americana (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"com Aliche Italiano (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Molhos","ITEM":"Alho e Óleo (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Molhos","ITEM":"à Bolonhesa (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"com Brócolis A&O (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"à calabresa (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"Gratinado (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"com Funghi Seco (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"à Michelangelo (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Molhos","ITEM":"à Etrusca (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"ao forno (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Risoto","ITEM":"de Funghi Seco","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Outros","ITEM":"Beringela Parm c/ Arroz (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Carne","ITEM":"Almondegas (3 Unidades)","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Carne","ITEM":"Mini Ropertone","ACTIVE":"TRUE","PRICE_MENU":"55,00","PRICE_DELIVERY":"55,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Guaraná","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Guaraná Zero","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Vinho","ITEM":"Taça 250ml Corte Antica Tinto","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Rolha","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Molhos","ITEM":"Porção de M. ao Sugo (500ml)","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"Porção de M. à Bolonhesa (500ml)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Café & Chá","ITEM":"Mate Leão (450ml)","ACTIVE":"TRUE","PRICE_MENU":"9,00","PRICE_DELIVERY":"9,00"},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Marietta Baderna","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Alho e Óleo A/F (200g ind)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Vinho","ITEM":"Taça 250ml Vinho Nacional Seco","ACTIVE":"TRUE","PRICE_MENU":"17,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Taça 250ml Vinho Nacional Suave","ACTIVE":"TRUE","PRICE_MENU":"17,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Jarra 500ml Vinho Nacional Seco","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Jarra 500ml Vinho Nacional Suave","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Jarra 1L Vinho Nacional Seco","ACTIVE":"TRUE","PRICE_MENU":"44,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Jarra 1L Vinho Nacional Suave","ACTIVE":"TRUE","PRICE_MENU":"44,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Sorvetes","ITEM":"Taça (2 bolas)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Milanesa s/ Acomp","ACTIVE":"TRUE","PRICE_MENU":"72,00","PRICE_DELIVERY":"72,00"},
  {"GROUP":"Frango","ITEM":"Frango à Milanesa A/F (ind)","ACTIVE":"TRUE","PRICE_MENU":"62,00","PRICE_DELIVERY":"62,00"},
  {"GROUP":"Antipasto","ITEM":"Sardela (100g)","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Molhos","ITEM":"Arrabiata","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Molhos","ITEM":"Arrabiata (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Empório","ITEM":"Ragu di Ossobuco 520g","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Outros","ITEM":"Combinado (ind)","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Outros","ITEM":"Embalagem","ACTIVE":"TRUE","PRICE_MENU":"3,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Empório","ITEM":"Ragu di Ossobuco 220g","ACTIVE":"TRUE","PRICE_MENU":"24,00","PRICE_DELIVERY":"24,00"},
  {"GROUP":"Empório","ITEM":"Ragu alla Bolognese 520g","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Empório","ITEM":"Ragu alla Bolognese 220g","ACTIVE":"TRUE","PRICE_MENU":"24,00","PRICE_DELIVERY":"24,00"},
  {"GROUP":"Empório","ITEM":"Sugo all'Arrabiata 310g","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Empório","ITEM":"Molho Siciliano 220g","ACTIVE":"TRUE","PRICE_MENU":"24,00","PRICE_DELIVERY":"24,00"},
  {"GROUP":"Empório","ITEM":"Molho Siciliano 520g","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Empório","ITEM":"Caldo de Galinha Caipira 300ml","ACTIVE":"TRUE","PRICE_MENU":"14,00","PRICE_DELIVERY":"14,00"},
  {"GROUP":"Empório","ITEM":"Caldo de Carne 300ml","ACTIVE":"TRUE","PRICE_MENU":"14,00","PRICE_DELIVERY":"14,00"},
  {"GROUP":"Empório","ITEM":"Caldo de Galinha Caipira 700ml","ACTIVE":"TRUE","PRICE_MENU":"21,00","PRICE_DELIVERY":"21,00"},
  {"GROUP":"Empório","ITEM":"Caldo de Carne 700ml","ACTIVE":"TRUE","PRICE_MENU":"21,00","PRICE_DELIVERY":"21,00"},
  {"GROUP":"Empório","ITEM":"Vinagre Balsamico IGP 500ml","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Empório","ITEM":"Suco de Limão Siciliano 200ml","ACTIVE":"TRUE","PRICE_MENU":"6,00","PRICE_DELIVERY":"6,00"},
  {"GROUP":"Empório","ITEM":"Tomate Pelati 2,5kg","ACTIVE":"TRUE","PRICE_MENU":"37,00","PRICE_DELIVERY":"37,00"},
  {"GROUP":"Empório","ITEM":"Fettuccine di Sardegna 500g","ACTIVE":"TRUE","PRICE_MENU":"11,00","PRICE_DELIVERY":"11,00"},
  {"GROUP":"Empório","ITEM":"Arroz Arbóreo di Sardegna 1kg","ACTIVE":"TRUE","PRICE_MENU":"26,00","PRICE_DELIVERY":"26,00"},
  {"GROUP":"Empório","ITEM":"Penne Rigate di Sardegna 500g","ACTIVE":"TRUE","PRICE_MENU":"11,00","PRICE_DELIVERY":"11,00"},
  {"GROUP":"Empório","ITEM":"Spaghetti n. 305 di Sardegna 500g","ACTIVE":"TRUE","PRICE_MENU":"11,00","PRICE_DELIVERY":"11,00"},
  {"GROUP":"Empório","ITEM":"Massa It Divella Rigatoni 500g","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Vinho","ITEM":"Lambrusco Chiarelli 750ml","ACTIVE":"TRUE","PRICE_MENU":"56,00","PRICE_DELIVERY":"36,00"},
  {"GROUP":"Vinho","ITEM":"Lambrusco Donnelli 750ml","ACTIVE":"TRUE","PRICE_MENU":"56,00","PRICE_DELIVERY":"36,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana A/F (200g meio)","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"110,00"},
  {"GROUP":"Salada","ITEM":"Salada Completa Grande","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Salada","ITEM":"Salada Completa Média","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Cervejas","ITEM":"Original (600ml)","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Empório","ITEM":"Geléia Troppo de Framboesa","ACTIVE":"TRUE","PRICE_MENU":"24,50","PRICE_DELIVERY":"24,50"},
  {"GROUP":"Empório","ITEM":"Geléia Troppo de Maçã c/ Canela","ACTIVE":"TRUE","PRICE_MENU":"24,50","PRICE_DELIVERY":"24,50"},
  {"GROUP":"Empório","ITEM":"Relish de Cebola Roxa","ACTIVE":"TRUE","PRICE_MENU":"24,50","PRICE_DELIVERY":"24,50"},
  {"GROUP":"Empório","ITEM":"Relish de Tomate com Funcho","ACTIVE":"TRUE","PRICE_MENU":"24,50","PRICE_DELIVERY":"24,50"},
  {"GROUP":"Empório","ITEM":"Queijo Tipo Grana Padano","ACTIVE":"TRUE","PRICE_MENU":"17,50","PRICE_DELIVERY":"17,50"},
  {"GROUP":"Empório","ITEM":"Queijo Caccio Cavalo","ACTIVE":"TRUE","PRICE_MENU":"37,00","PRICE_DELIVERY":"37,00"},
  {"GROUP":"Empório","ITEM":"Kit de Queijo, Faca e Tábula","ACTIVE":"TRUE","PRICE_MENU":"85,00","PRICE_DELIVERY":"85,00"},
  {"GROUP":"Couvert","ITEM":"Couvert Comp c/ pães e Mant","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Vinho","ITEM":"Leon Tarapaca 750ml Carmenere","ACTIVE":"TRUE","PRICE_MENU":"97,00","PRICE_DELIVERY":"63,00"},
  {"GROUP":"Empório","ITEM":"Burrata","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Vegetariano","ITEM":"Almondegas Vegetarianas (8 unidades)","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Ginger Prata (Lata)","ACTIVE":"TRUE","PRICE_MENU":"9,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica Indian Prata (Garrafa)","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Cervejas","ITEM":"Serramalte (600ml)","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Doces","ITEM":"Torta Sonho de Valsa","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Doces","ITEM":"Tiramisu Grande","ACTIVE":"TRUE","PRICE_MENU":"18,00","PRICE_DELIVERY":"18,00"},
  {"GROUP":"Doces","ITEM":"Torta Sonho de Valsa Grande","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Café & Chá","ITEM":"Salton - Chá Preto Frutas Vermelhas","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Café & Chá","ITEM":"Salton - Chá Preto Tangerina","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Café & Chá","ITEM":"Salton - Chá Verde","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Café & Chá","ITEM":"Salton - Chá Branco","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Cervejas","ITEM":"Stella Artois (550ml)","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Salton - Suco Integral de Uva","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Antipasto","ITEM":"Burrata com Tomate Seco","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Aperitivos","ITEM":"da Casa","ACTIVE":"TRUE","PRICE_MENU":"15,00","PRICE_DELIVERY":"15,00"},
  {"GROUP":"Antipasto","ITEM":"Burrata ao Tartufo Branco com Tomate Seco","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Empório","ITEM":"Burrata ao Tartufo","ACTIVE":"TRUE","PRICE_MENU":"23,00","PRICE_DELIVERY":"23,00"},
  {"GROUP":"Mercato","ITEM":"Polvilho Azedo Canastra","ACTIVE":"TRUE","PRICE_MENU":"18,00","PRICE_DELIVERY":"18,00"},
  {"GROUP":"Mercato","ITEM":"Café Canastra","ACTIVE":"TRUE","PRICE_MENU":"22,00","PRICE_DELIVERY":"22,00"},
  {"GROUP":"Mercato","ITEM":"Maturador de Queijo Canastra","ACTIVE":"TRUE","PRICE_MENU":"250,00","PRICE_DELIVERY":"250,00"},
  {"GROUP":"Mercato","ITEM":"Goiabada","ACTIVE":"TRUE","PRICE_MENU":"17,00","PRICE_DELIVERY":"17,00"},
  {"GROUP":"Mercato","ITEM":"Doce de Abóbora","ACTIVE":"TRUE","PRICE_MENU":"29,00","PRICE_DELIVERY":"29,00"},
  {"GROUP":"Salada","ITEM":"Palmito (individual)","ACTIVE":"TRUE","PRICE_MENU":"40,00","PRICE_DELIVERY":"40,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco del Valle Uva (290ml)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco del Valle Maracujá (290ml)","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco del Valle Laranja (250ml)","ACTIVE":"TRUE","PRICE_MENU":"7,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Cervejas","ITEM":"Heineken (600ml)","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Empório","ITEM":"Azeite O-live","ACTIVE":"TRUE","PRICE_MENU":"32,00","PRICE_DELIVERY":"32,00"},
  {"GROUP":"Molhos","ITEM":"com Frutos do Mar (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"80,00","PRICE_DELIVERY":"80,00"},
  {"GROUP":"Mercato","ITEM":"Azeitona Verde Recheada 195g","ACTIVE":"TRUE","PRICE_MENU":"12,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Mercato","ITEM":"Azeito Verde Raiolita 180g","ACTIVE":"TRUE","PRICE_MENU":"7,00","PRICE_DELIVERY":"7,00"},
  {"GROUP":"Mercato","ITEM":"Tomate Pelado Italiano 400g","ACTIVE":"TRUE","PRICE_MENU":"8,50","PRICE_DELIVERY":"8,50"},
  {"GROUP":"Mercato","ITEM":"Vinagre de Vinho Tinto Raiola 500ml","ACTIVE":"TRUE","PRICE_MENU":"16,00","PRICE_DELIVERY":"16,00"},
  {"GROUP":"Mercato","ITEM":"Tremoço Raiola 200g","ACTIVE":"TRUE","PRICE_MENU":"12,00","PRICE_DELIVERY":"12,00"},
  {"GROUP":"Mercato","ITEM":"Suco de Tomate Raiola 500ml","ACTIVE":"TRUE","PRICE_MENU":"13,00","PRICE_DELIVERY":"13,00"},
  {"GROUP":"Mercato","ITEM":"Mini Chocotone com M&Ms","ACTIVE":"TRUE","PRICE_MENU":"10,00","PRICE_DELIVERY":"10,00"},
  {"GROUP":"Mercato","ITEM":"Arroz Arbóreo La Pastina","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Mercato","ITEM":"Crostini Sal Marinho e Alecrim","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Mercato","ITEM":"Crostini Parmesão e Pecorino","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Mercato","ITEM":"Tarallo Mediterrâneo","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Mercato","ITEM":"Fundo de Alcachofra","ACTIVE":"TRUE","PRICE_MENU":"22,00","PRICE_DELIVERY":"22,00"},
  {"GROUP":"Mercato","ITEM":"Aspargo Verde","ACTIVE":"TRUE","PRICE_MENU":"31,00","PRICE_DELIVERY":"31,00"},
  {"GROUP":"Mercato","ITEM":"Bruscheta de Alcachofra","ACTIVE":"TRUE","PRICE_MENU":"24,00","PRICE_DELIVERY":"24,00"},
  {"GROUP":"Mercato","ITEM":"Molho de Alcachofra","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Mercato","ITEM":"Molho Putanesca","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Mercato","ITEM":"Alcachofra na Brasa","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Mercato","ITEM":"Chá Carmencita de Gengibre e Mel","ACTIVE":"TRUE","PRICE_MENU":"18,00","PRICE_DELIVERY":"18,00"},
  {"GROUP":"Mercato","ITEM":"Carpaccio di Tartufo","ACTIVE":"TRUE","PRICE_MENU":"132,00","PRICE_DELIVERY":"132,00"},
  {"GROUP":"Mercato","ITEM":"Crema di Carciofi e Tartufo","ACTIVE":"TRUE","PRICE_MENU":"57,00","PRICE_DELIVERY":"57,00"},
  {"GROUP":"Mercato","ITEM":"Funghi Porcini Sechi","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Mercato","ITEM":"Salsa di Olive e Tartufo","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Mercato","ITEM":"Mix Vegetais na Brasa","ACTIVE":"TRUE","PRICE_MENU":"27,00","PRICE_DELIVERY":"27,00"},
  {"GROUP":"Mercato","ITEM":"Tortellini 3 Queijos","ACTIVE":"TRUE","PRICE_MENU":"20,00","PRICE_DELIVERY":"20,00"},
  {"GROUP":"Mercato","ITEM":"Bucatini Divella","ACTIVE":"TRUE","PRICE_MENU":"8,00","PRICE_DELIVERY":"8,00"},
  {"GROUP":"Mercato","ITEM":"Pomodori Pelati Organico","ACTIVE":"TRUE","PRICE_MENU":"10,50","PRICE_DELIVERY":"10,50"},
  {"GROUP":"Empório","ITEM":"Ragu di Mare 220g","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Molhos","ITEM":"ao Vongolis (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"30,00","PRICE_DELIVERY":"30,00"},
  {"GROUP":"Molhos","ITEM":"com Camarões (ind ou 1/2)","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"110,00"},
  {"GROUP":"Filé Mignon","ITEM":"Filé com Brócolis e Arroz (400g)","ACTIVE":"TRUE","PRICE_MENU":"140,00","PRICE_DELIVERY":"140,00"},
  {"GROUP":"Filé Mignon","ITEM":"Filé com Brócolis e Arroz (200g ind)","ACTIVE":"TRUE","PRICE_MENU":"85,00","PRICE_DELIVERY":"85,00"},
  {"GROUP":"Massas","ITEM":"Porção Massa sem Recheio (kg)","ACTIVE":"TRUE","PRICE_MENU":"60,00","PRICE_DELIVERY":"60,00"},
  {"GROUP":"Massas","ITEM":"Porção Masssa com Recheio (kg)","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa A/F (200g meio)","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (meio 200g)","ACTIVE":"TRUE","PRICE_MENU":"110,00","PRICE_DELIVERY":"110,00"},
  {"GROUP":"Frango","ITEM":"Frango à Milanesa A/F (grande)","ACTIVE":"TRUE","PRICE_MENU":"100,00","PRICE_DELIVERY":"100,00"},
  {"GROUP":"Frango","ITEM":"1/2 Frango à Parmigiana Simples","ACTIVE":"TRUE","PRICE_MENU":"62,00","PRICE_DELIVERY":"0,00"},
  {"GROUP":"Peixe","ITEM":"Pescada c/ Purê e Grega","ACTIVE":"TRUE","PRICE_MENU":"140,00","PRICE_DELIVERY":"140,00"},
  {"GROUP":"Peixe","ITEM":"Meio Pescada c/ Purê e Grega","ACTIVE":"TRUE","PRICE_MENU":"90,00","PRICE_DELIVERY":"90,00"},
  {"GROUP":"Sugestões","ITEM":"Combo Bucatini com Parmegiana (ind)","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Sugestões","ITEM":"Combo Fet c/ Funghi e Milanesa","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Sugestões","ITEM":"Combo Fet c/ Funghi e Chapa","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Massas","ITEM":"Lasanha Verde","ACTIVE":"TRUE","PRICE_MENU":"65,00","PRICE_DELIVERY":"65,00"},
  {"GROUP":"Massas","ITEM":"Lasanha Verde (ind)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Massas","ITEM":"Mini Cannelloni Vegetais (ind)","ACTIVE":"TRUE","PRICE_MENU":"50,00","PRICE_DELIVERY":"50,00"},
  {"GROUP":"Massas","ITEM":"Gnocchi de Abobora (ind)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Massas","ITEM":"Gnocchi de Mandioquinha","ACTIVE":"TRUE","PRICE_MENU":"75,00","PRICE_DELIVERY":"75,00"},
  {"GROUP":"Massas","ITEM":"Gnocchi de Mand. (ind)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Sopas","ITEM":"Cap Brodo Queijo","ACTIVE":"TRUE","PRICE_MENU":"85,00","PRICE_DELIVERY":"85,00"},
  {"GROUP":"Sopas","ITEM":"Cap Brodo Queijo (ind)","ACTIVE":"TRUE","PRICE_MENU":"45,00","PRICE_DELIVERY":"45,00"},
  {"GROUP":"Mercato","ITEM":"Confetti com Mandorla e Cioccolato","ACTIVE":"TRUE","PRICE_MENU":"35,00","PRICE_DELIVERY":"35,00"},
  {"GROUP":"Mercato","ITEM":"Cime di Rapa","ACTIVE":"TRUE","PRICE_MENU":"49,00","PRICE_DELIVERY":"49,00"},
  {"GROUP":"Mercato","ITEM":"Pepininho","ACTIVE":"TRUE","PRICE_MENU":"31,00","PRICE_DELIVERY":"31,00"},
  {"GROUP":"Mercato","ITEM":"Azeite Trufado","ACTIVE":"TRUE","PRICE_MENU":"53,00","PRICE_DELIVERY":"53,00"},
  {"GROUP":"Mercato","ITEM":"Molho Barbecue","ACTIVE":"TRUE","PRICE_MENU":"25,00","PRICE_DELIVERY":"25,00"},
  {"GROUP":"Mercato","ITEM":"Tonno alla Siciliana","ACTIVE":"TRUE","PRICE_MENU":"31,00","PRICE_DELIVERY":"31,00"},
  {"GROUP":"Mercato","ITEM":"Farfalle Divela Colorido","ACTIVE":"TRUE","PRICE_MENU":"17,00","PRICE_DELIVERY":"17,00"},
  {"GROUP":"Mercato","ITEM":"Salsa Campera","ACTIVE":"TRUE","PRICE_MENU":"19,00","PRICE_DELIVERY":"19,00"},
  {"GROUP":"Mercato","ITEM":"Penne Divella","ACTIVE":"TRUE","PRICE_MENU":"11,00","PRICE_DELIVERY":"11,00"},
  {"GROUP":"Empório","ITEM":"Penne Integral Divella","ACTIVE":"TRUE","PRICE_MENU":"13,00","PRICE_DELIVERY":"13,00"}
];

export default dadosDeliveryItems;