const dadosDeliveryItems = [
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Água de Côco","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Água Mineral com Gás","ACTIVE":"TRUE","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Água Mineral sem Gás","ACTIVE":"TRUE","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Coca-Cola (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Coca-Cola Zero (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Fanta Laranja (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Fanta Uva (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Ginger Prata (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":7,"PRICE_MENU":9},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Guaraná","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Guaraná Zero","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"H2OH! Limão","ACTIVE":"TRUE","PRICE_DELIVERY":7,"PRICE_MENU":9},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"H2OH! Limoneto","ACTIVE":"TRUE","PRICE_DELIVERY":7,"PRICE_MENU":9},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Soda Limonada (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Soda Limonada Zero (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Abacaxi","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Abacaxi com Hortelã","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Acerola","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Cajá","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Cajú","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Laranja","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Manga","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Maracujá","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Melancia","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Melão","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de morango","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Tomate","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Uva","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Suco de Uva Integral Perini","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica Indian Prata (Garrafa)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica schweppes (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica schweppes Diet/Light (Lata)","ACTIVE":"FALSE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica schweppes Limão (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica schweppes Limão Diet/Light (Lata)","ACTIVE":"FALSE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Água, Sucos e Refrigerantes","ITEM":"Tônica Zero (Lata)","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Antipasto","ITEM":"Abobrinha (150g)","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":20},
  {"GROUP":"Antipasto","ITEM":"Aliche Italiano (90g di salerno)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":70},
  {"GROUP":"Antipasto","ITEM":"Antipasto (2 cestas de pães ou 1 filão)","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Antipasto","ITEM":"Antipasto Médio (1 cesta de pães ou meio filão)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Antipasto","ITEM":"Azeitonas Azapa (200g Raiola)","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":20},
  {"GROUP":"Antipasto","ITEM":"Berinjela a Vinagrete (uma banda)","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":18},
  {"GROUP":"Antipasto","ITEM":"Berinjela all'Inferno (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Berinjela Recheada (uma banda)","ACTIVE":"TRUE","PRICE_DELIVERY":24,"PRICE_MENU":28},
  {"GROUP":"Antipasto","ITEM":"Calabresa","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Antipasto","ITEM":"Caponata (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Pasta de Pimentão Verde e Ricota (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Pimentão Rosso (100g)","ACTIVE":"TRUE","PRICE_DELIVERY":22,"PRICE_MENU":28},
  {"GROUP":"Antipasto","ITEM":"Provolone (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Salada napolitana (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Salame (100g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Antipasto","ITEM":"Sardela (100g)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Antipasto","ITEM":"Sardela (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":27},
  {"GROUP":"Antipasto","ITEM":"Tomate Seco (200g)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":25},
  {"GROUP":"Aperitivos","ITEM":"Campari","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Cynar","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Aperitivos","ITEM":"Gin Gordon's","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Aperitivos","ITEM":"Gin Seagers","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Rum bacardi Ouro","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Rum Bacardi Prata","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Sakê Azuma","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Steinhaeger Becosa","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Aperitivos","ITEM":"Steinhäger Schilichte","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Aperitivos","ITEM":"Tequila José Cuervo Oro","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Aperitivos","ITEM":"Underberg","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Brandy e Conhaques","ITEM":"Domecq","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Brandy e Conhaques","ITEM":"Fundador","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Brandy e Conhaques","ITEM":"Macieira Royal Brand","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Cabrito","ITEM":"à Caçadora com Polentas fritas","ACTIVE":"TRUE","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Cabrito","ITEM":"à Caçadora com Polentas fritas (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Cabrito","ITEM":"ao Forno com Batatas coradas","ACTIVE":"TRUE","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Cabrito","ITEM":"ao Forno com Batatas coradas (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Cabrito","ITEM":"Perna Traseira com Brócolis alho e óleo e Batatas ao forno","ACTIVE":"TRUE","PRICE_DELIVERY":260,"PRICE_MENU":260},
  {"GROUP":"Cachaças","ITEM":"Espirito de Minas - MG","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Cachaças","ITEM":"Sagatiba Prata - SP","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Cachaças","ITEM":"Salinas - MG","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Cachaças","ITEM":"Santo Grau - MG","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Café & Chá","ITEM":"Café com Sambuca","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Café & Chá","ITEM":"Café Correto (com grappa)","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Café & Chá","ITEM":"Café Expresso","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Café & Chá","ITEM":"Café Macchiato","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Café & Chá","ITEM":"Chá ou Infusão","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Café & Chá","ITEM":"Mate Leão (450ml)","ACTIVE":"TRUE","PRICE_DELIVERY":9,"PRICE_MENU":9},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Absolut","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Espirito de Minas","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Sagatiba","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Sakê","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Salinas","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Santo Grau","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Smirnoff","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Steinhaeger Becosa","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Caipirinhas","ITEM":"Caipirinha de Stolichnaya","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Caipirinhas","ITEM":"Caipirosca de Rum","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Carne","ITEM":"Almondegas (3 Unidades)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Carne","ITEM":"Almondegas (6 Unidades)","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Carne","ITEM":"Brachola (1 Unidade)","ACTIVE":"TRUE","PRICE_DELIVERY":38,"PRICE_MENU":38},
  {"GROUP":"Carne","ITEM":"Mini Ropertone","ACTIVE":"TRUE","PRICE_DELIVERY":55,"PRICE_MENU":55},
  {"GROUP":"Carne","ITEM":"Mini Ropertone com arroz","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":65},
  {"GROUP":"Carne","ITEM":"Ropertone","ACTIVE":"TRUE","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Cervejas","ITEM":"Heineken (Longneck)","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Cervejas","ITEM":"Original (600ml)","ACTIVE":"TRUE","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Cervejas","ITEM":"Stella Artois (Longneck)","ACTIVE":"TRUE","PRICE_DELIVERY":12,"PRICE_MENU":12},
  {"GROUP":"Couvert","ITEM":"Cesta de Pães tipo Italiano","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":8},
  {"GROUP":"Couvert","ITEM":"Completo de 2ª a 6ª Almoço","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Couvert","ITEM":"Completo de FinDe, Feriado e Jantar","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Couvert","ITEM":"Couvert Comp com cesta de pães","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":15},
  {"GROUP":"Couvert","ITEM":"Couvert Comp com pães e Mant","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Couvert","ITEM":"Filão de pão tipo italiano (Basilicata)","ACTIVE":"TRUE","PRICE_DELIVERY":13,"PRICE_MENU":13},
  {"GROUP":"Couvert","ITEM":"Meio filão de pão tipo italiano (Basilicata)","ACTIVE":"TRUE","PRICE_DELIVERY":7,"PRICE_MENU":7},
  {"GROUP":"Couvert","ITEM":"Pão tipo Italiano com Manteiga","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":13},
  {"GROUP":"Digestivos","ITEM":"Fernet Branca","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Digestivos","ITEM":"Grappa Giovane - IT","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Digestivos","ITEM":"Grappa Invecchiata - IT","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Doces","ITEM":"Panna Cotta","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Doces","ITEM":"Pastiera de Grão","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Doces","ITEM":"Petit Gateau","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Doces","ITEM":"Pudim de Caramelo","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Doces","ITEM":"Tiramisu","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Drinks","ITEM":"Aperol Spritz","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Bloody mary","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Cuba-Libre","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Gin Tônica","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Drinks","ITEM":"Negroni","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Drinks","ITEM":"Sbagliato","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Empório","ITEM":"Arroz It Arbóreo Riso di Sardegna 1kg","ACTIVE":"TRUE","PRICE_DELIVERY":26,"PRICE_MENU":26},
  {"GROUP":"Empório","ITEM":"Caldo de Carne 300ml","ACTIVE":"TRUE","PRICE_DELIVERY":14,"PRICE_MENU":14},
  {"GROUP":"Empório","ITEM":"Caldo de Carne 700ml","ACTIVE":"TRUE","PRICE_DELIVERY":21,"PRICE_MENU":21},
  {"GROUP":"Empório","ITEM":"Caldo de Galinha Caipira 300ml","ACTIVE":"TRUE","PRICE_DELIVERY":14,"PRICE_MENU":14},
  {"GROUP":"Empório","ITEM":"Caldo de Galinha Caipira 700ml","ACTIVE":"TRUE","PRICE_DELIVERY":21,"PRICE_MENU":21},
  {"GROUP":"Empório","ITEM":"Condimento Suco de Limão Siciliano 200ml","ACTIVE":"TRUE","PRICE_DELIVERY":6,"PRICE_MENU":6},
  {"GROUP":"Empório","ITEM":"Geléia Troppo de Framboesa","ACTIVE":"TRUE","PRICE_DELIVERY":24,5,"PRICE_MENU":24,5},
  {"GROUP":"Empório","ITEM":"Geléia Troppo de Maçã com Canela","ACTIVE":"TRUE","PRICE_DELIVERY":24,5,"PRICE_MENU":24,5},
  {"GROUP":"Empório","ITEM":"Kit de Queijo, Faca e Tábula","ACTIVE":"TRUE","PRICE_DELIVERY":85,"PRICE_MENU":85},
  {"GROUP":"Empório","ITEM":"Massa It Divella Rigatoni 500g","ACTIVE":"TRUE","PRICE_DELIVERY":8,"PRICE_MENU":8},
  {"GROUP":"Empório","ITEM":"Massa It Fettuccine - Pasta di Sardegna 500g","ACTIVE":"TRUE","PRICE_DELIVERY":11,"PRICE_MENU":11},
  {"GROUP":"Empório","ITEM":"Massa It Penne Rigate Pasta di Sardegna 500g","ACTIVE":"TRUE","PRICE_DELIVERY":11,"PRICE_MENU":11},
  {"GROUP":"Empório","ITEM":"Massa It Spaghetti n. 305 Pasta di Sardegna 500g","ACTIVE":"TRUE","PRICE_DELIVERY":11,"PRICE_MENU":11},
  {"GROUP":"Empório","ITEM":"Molho It Tomate Pelati 2,5kg","ACTIVE":"TRUE","PRICE_DELIVERY":37,"PRICE_MENU":37},
  {"GROUP":"Empório","ITEM":"Molho Siciliano 220g","ACTIVE":"TRUE","PRICE_DELIVERY":24,"PRICE_MENU":24},
  {"GROUP":"Empório","ITEM":"Molho Siciliano 520g","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Empório","ITEM":"Queijo Caccio Cavalo","ACTIVE":"TRUE","PRICE_DELIVERY":37,"PRICE_MENU":37},
  {"GROUP":"Empório","ITEM":"Queijo Tipo Grana Padano","ACTIVE":"TRUE","PRICE_DELIVERY":17,5,"PRICE_MENU":17,5},
  {"GROUP":"Empório","ITEM":"Ragu alla Bolognese 220g","ACTIVE":"TRUE","PRICE_DELIVERY":24,"PRICE_MENU":24},
  {"GROUP":"Empório","ITEM":"Ragu alla Bolognese 520g","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Empório","ITEM":"Ragu di Ossobuco 220g","ACTIVE":"TRUE","PRICE_DELIVERY":24,"PRICE_MENU":24},
  {"GROUP":"Empório","ITEM":"Ragu di Ossobuco 520g","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Empório","ITEM":"Relish de Cebola Roxa","ACTIVE":"TRUE","PRICE_DELIVERY":24,5,"PRICE_MENU":24,5},
  {"GROUP":"Empório","ITEM":"Relish de Tomate com Funcho","ACTIVE":"TRUE","PRICE_DELIVERY":24,5,"PRICE_MENU":24,5},
  {"GROUP":"Empório","ITEM":"Sugo all'Arrabiata 310g","ACTIVE":"TRUE","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Empório","ITEM":"Vinagre It Balsamico de Modena IGP 500ml","ACTIVE":"TRUE","PRICE_DELIVERY":16,"PRICE_MENU":16},
  {"GROUP":"Filé Mignon","ITEM":"à Cordonbleu (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":130,"PRICE_MENU":130},
  {"GROUP":"Filé Mignon","ITEM":"à Cubana (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":130,"PRICE_MENU":130},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa (200g sem acompanhamento)","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa (400g sem acompanhamento)","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa com Arroz e Fritas  (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":130,"PRICE_MENU":130},
  {"GROUP":"Filé Mignon","ITEM":"à Milanesa com Arroz e Fritas (200g individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":75},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana (400g sem acompanhamento)","ACTIVE":"TRUE","PRICE_DELIVERY":130,"PRICE_MENU":130},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana (médio 200g sem acompanhamento)","ACTIVE":"TRUE","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana A/F (200g individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana A/F (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":148,"PRICE_MENU":148},
  {"GROUP":"Filé Mignon","ITEM":"à Parmigiana A/F (antigo meio)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":110},
  {"GROUP":"Filé Mignon","ITEM":"à Pizzaiolo (400g com aliche IT di salerno)","ACTIVE":"TRUE","PRICE_DELIVERY":160,"PRICE_MENU":160},
  {"GROUP":"Filé Mignon","ITEM":"à Roperto (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":150,"PRICE_MENU":150},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (200g individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"aos 4 Queijos (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":148,"PRICE_MENU":148},
  {"GROUP":"Filé Mignon","ITEM":"d'Alê (200g individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":90},
  {"GROUP":"Filé Mignon","ITEM":"d'Alê (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":143,"PRICE_MENU":143},
  {"GROUP":"Filé Mignon","ITEM":"Escalope à Vienense (200g Individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"Escalope à Vienense (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":148,"PRICE_MENU":148},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado (Médio 200g)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Alho e Óleo (200g individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado Alho e Óleo (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado com fritas (200g Individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":80},
  {"GROUP":"Filé Mignon","ITEM":"Grelhado com Fritas (400g)","ACTIVE":"TRUE","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Frango","ITEM":"1/2 desossado a Cubana","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado com Brócolis","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado com Creme de Milho","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado com Purê e Champignon","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"1/2 desossado Grelhado","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"a Passarinho 1/1","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Frango","ITEM":"a passarinho 1/2","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Marietta Baderna","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":72},
  {"GROUP":"Frango","ITEM":"Filé de Frango à Milanesa sem Acompanhamento","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Frango","ITEM":"Peito de Frango à Milanesa com Arroz e Fritas (individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":60},
  {"GROUP":"Frango","ITEM":"Peito de Frango à Parmigiana com Arroz e Fritas","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Frango","ITEM":"Peito de Frango à Parmigiana com Arroz e Fritas (individual)","ACTIVE":"TRUE","PRICE_DELIVERY":66,"PRICE_MENU":66},
  {"GROUP":"Frutas","ITEM":"Abacaxi","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Creme de Manga","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Creme de Papaya","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Mamão","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Manga","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Melão","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Frutas","ITEM":"Salada de Frutas","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Infantil","ITEM":"Escalopine, Arroz e Fritas","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Infantil","ITEM":"Espaguete ao Sugo com Almondega","ACTIVE":"TRUE","PRICE_DELIVERY":38,"PRICE_MENU":38},
  {"GROUP":"Infantil","ITEM":"Espaguete com Escalopine","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Licores","ITEM":"Amaretto d'Orso","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Amaro","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Amarula","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Baileys","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Cointreau","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Licores","ITEM":"Drambui","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Frangelico","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Licor 43","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Licor de Cassis Jean Dijon","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Limoncello","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Mandarineto Isolabella","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Maraschino","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Peach Tree","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Sambuca IT","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Licores","ITEM":"Strega IT","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Massas","ITEM":"Agnolotti","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Agnolotti (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Agnolotti Verde Abób","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Agnolotti Verde Abób (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Canelloni Branco (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Canelloni verde (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Canelone Branco","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Canelone Verde","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Cappelletti","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Cappelletti (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Espaguete","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Espaguete (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Fetuccine branco","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Fetuccine Branco (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Fetuccine verde","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Fetuccine Verde (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Fusilli","ACTIVE":"TRUE","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Massas","ITEM":"Fusilli (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Massas","ITEM":"Gnocchi de Batata","ACTIVE":"TRUE","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Massas","ITEM":"Gnocchi de Batata (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Massas","ITEM":"Lasanha","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Massas","ITEM":"Lasanha (individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Penne","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Penne (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Ravioli de Carne","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Ravioli de Carne (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Ravioli de Mussarela de Búfala","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Ravioli de Mussarela de Búfala (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Ravioli de Ricota","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Ravioli de Ricota (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas","ITEM":"Richitelli","ACTIVE":"TRUE","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Massas","ITEM":"Richitelli (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Massas","ITEM":"Rigatone","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Massas","ITEM":"Rigatone (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Massas","ITEM":"Rondelli","ACTIVE":"TRUE","PRICE_DELIVERY":80,"PRICE_MENU":80},
  {"GROUP":"Massas","ITEM":"Rondelli (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas Especiais","ITEM":"Espaguete Integral (individual)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Massas Especiais","ITEM":"Penne sem Glúten (individual)","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Molhos","ITEM":"à Bolonhesa","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Bolonhesa (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à calabresa","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"à calabresa (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"à Carbonara Americana","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Molhos","ITEM":"à Carbonara Americana (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Etrusca","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Etrusca (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"à Genovesa","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Genovesa (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Michelangelo","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Michelangelo (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Napolitana","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"à Napolitana (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":5,"PRICE_MENU":5},
  {"GROUP":"Molhos","ITEM":"à Parisiense","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Parisiense (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Putanesca","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Putanesca (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"à Romanesca","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"à Romanesca (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"Alho e Óleo","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"Alho e Óleo (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":5,"PRICE_MENU":5},
  {"GROUP":"Molhos","ITEM":"ao forno","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"ao forno (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"ao Pesto de Nossa Familia","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"ao Pesto de Nossa Familia (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"ao Sugo","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"ao Sugo (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":5,"PRICE_MENU":5},
  {"GROUP":"Molhos","ITEM":"ao Vongolis","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Molhos","ITEM":"aos Quatro Queijos","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Molhos","ITEM":"aos Quatro Queijos (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Molhos","ITEM":"Arrabiata","ACTIVE":"TRUE","PRICE_DELIVERY":10,"PRICE_MENU":10},
  {"GROUP":"Molhos","ITEM":"Arrabiata (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":5,"PRICE_MENU":5},
  {"GROUP":"Molhos","ITEM":"com Aliche Italiano di Salerno","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Molhos","ITEM":"com Aliche Italiano di Salerno (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Molhos","ITEM":"com Brócolis Alho e Óleo","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"com Brócolis Alho e Óleo (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"com Funghi Seco","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"com Funghi Seco (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"Gratinado","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"Gratinado (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Molhos","ITEM":"Porção de molho à Bolonhesa (600ml)","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":0},
  {"GROUP":"Molhos","ITEM":"Porção de molho ao Sugo (600ml)","ACTIVE":"TRUE","PRICE_DELIVERY":26,"PRICE_MENU":0},
  {"GROUP":"Molhos","ITEM":"Rosé","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Molhos","ITEM":"Rosé (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Outros","ITEM":"Beringela à Parmigiana com Arroz","ACTIVE":"TRUE","PRICE_DELIVERY":88,"PRICE_MENU":88},
  {"GROUP":"Outros","ITEM":"Beringela à Parmigiana com Arroz (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Outros","ITEM":"Combinado (individual)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":90},
  {"GROUP":"Outros","ITEM":"Embalagem","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":3},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada a Dorê com Molho de Camarão e Arroz p/1","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada a Dorê com Molho de Camarão e Arroz p/2","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada a Dorê com Purê e Brócolis p/1","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Peixe","ITEM":"Filé de Pescada a Dorê com Purê e Brócolis p/2","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Porções","ITEM":"Arroz","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porções","ITEM":"Arroz à Grega","ACTIVE":"TRUE","PRICE_DELIVERY":34,"PRICE_MENU":34},
  {"GROUP":"Porções","ITEM":"Bananas à Milanesa (2 Unidades)","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porções","ITEM":"Batata Frita","ACTIVE":"TRUE","PRICE_DELIVERY":27,"PRICE_MENU":27},
  {"GROUP":"Porções","ITEM":"Brócolis Alho e Óleo","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Porções","ITEM":"Brócolis com Catupiry","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Porções","ITEM":"Creme de Milho","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Porções","ITEM":"Polenta Frita","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Porções","ITEM":"Purê de Batatas","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Porto","ITEM":"Adriano Ramos Pinto","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":35},
  {"GROUP":"Porto","ITEM":"Dom José","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Risoto","ITEM":"de Camarão","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Risoto","ITEM":"de Frango","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":70},
  {"GROUP":"Risoto","ITEM":"de Frutos do Mar","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Risoto","ITEM":"de Funghi Seco","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":90},
  {"GROUP":"Salada","ITEM":"Brócolis","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Carpaccio","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Completa Individual","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Completa Tradicional","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Escarola, Salsão, Bacon & Alho","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Salada","ITEM":"Escarola, Salsão, Bacon & Alho (Média)","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Salada","ITEM":"Mista (Escarola, Tomate, palmito, Bacon, salsão e Alho)","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Salada","ITEM":"Mista (Média Escarola, Tomate, palmito, Bacon, salsão e Alho)","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Salada","ITEM":"Palmito","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Palmito e Brócolis","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Salada Completa (Escarola, Tomate, palmito, Bacon, Salsão, Alho, Alface e Ovo Cozido)","ACTIVE":"TRUE","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Salada","ITEM":"Salada Completa (Média Escarola, Tomate, palmito, Bacon, Salsão, Alho, Alface e Ovo Cozido))","ACTIVE":"TRUE","PRICE_DELIVERY":50,"PRICE_MENU":50},
  {"GROUP":"Salada","ITEM":"Tomate","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Salada","ITEM":"Tomate e Palmito","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Salada","ITEM":"Tomate e palmito (média)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Salada","ITEM":"Verdes","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Sopas","ITEM":"Canja","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Sopas","ITEM":"Canja (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Sopas","ITEM":"Cappelletti in Brodo","ACTIVE":"TRUE","PRICE_DELIVERY":75,"PRICE_MENU":75},
  {"GROUP":"Sopas","ITEM":"Cappelletti in Brodo (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":45,"PRICE_MENU":45},
  {"GROUP":"Sopas","ITEM":"Minestrone de legumes","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Sopas","ITEM":"Minestrone de legumes (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":40},
  {"GROUP":"Sorvetes","ITEM":"Colegial","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Sorvetes","ITEM":"Taça (1 bola)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":10},
  {"GROUP":"Sorvetes","ITEM":"Taça (2 bolas)","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":15},
  {"GROUP":"Sorvetes","ITEM":"Tartufo","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Sugestões","ITEM":"Agnolotti Gratinato","ACTIVE":"TRUE","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Sugestões","ITEM":"Agnolotti Gratinato (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Sugestões","ITEM":"Agnolotti Verde Abób Rose","ACTIVE":"TRUE","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Sugestões","ITEM":"Agnolotti Verde Abób Rose (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Sugestões","ITEM":"Canelone Verde ao Forno","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Sugestões","ITEM":"Canelone Verde ao Forno (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Sugestões","ITEM":"Cappelletti à Romanesca","ACTIVE":"TRUE","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Sugestões","ITEM":"Cappelletti à Romanesca (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Sugestões","ITEM":"Espaguete com Almondegas","ACTIVE":"TRUE","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Sugestões","ITEM":"Espaguete com Almondegas (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Sugestões","ITEM":"Fettuccine ao Pesto","ACTIVE":"TRUE","PRICE_DELIVERY":95,"PRICE_MENU":95},
  {"GROUP":"Sugestões","ITEM":"Fettuccine ao Pesto (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":55,"PRICE_MENU":55},
  {"GROUP":"Sugestões","ITEM":"Fusili à Calabresa","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Sugestões","ITEM":"Fusili à Calabresa (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Sugestões","ITEM":"Gnocchi à Michelangelo","ACTIVE":"TRUE","PRICE_DELIVERY":105,"PRICE_MENU":105},
  {"GROUP":"Sugestões","ITEM":"Gnocchi à Michelangelo (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":65},
  {"GROUP":"Sugestões","ITEM":"Lasanha à Bolonhesa","ACTIVE":"TRUE","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Sugestões","ITEM":"Lasanha à Bolonhesa (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Sugestões","ITEM":"Penne à Putanesca","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Sugestões","ITEM":"Penne à Putanesca (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Sugestões","ITEM":"Ravioli de Muss de Búf à Nap","ACTIVE":"TRUE","PRICE_DELIVERY":90,"PRICE_MENU":90},
  {"GROUP":"Sugestões","ITEM":"Ravioli de Muss de Búf à Nap (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":55,"PRICE_MENU":55},
  {"GROUP":"Sugestões","ITEM":"Richitelle salsa Rose","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Sugestões","ITEM":"Richitelle Salsa Rose (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Sugestões","ITEM":"Rigatone à Genovesa","ACTIVE":"TRUE","PRICE_DELIVERY":100,"PRICE_MENU":100},
  {"GROUP":"Sugestões","ITEM":"Rigatone à Genovesa (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":60},
  {"GROUP":"Sugestões","ITEM":"Rondelle aos Quatro Queijos","ACTIVE":"TRUE","PRICE_DELIVERY":110,"PRICE_MENU":110},
  {"GROUP":"Sugestões","ITEM":"Rondelle aos Quatro Queijos (individual ou meia porção)","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":70},
  {"GROUP":"Tortas Geladas","ITEM":"Alemã","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Tortas Geladas","ITEM":"Almendrado","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Tortas Geladas","ITEM":"de Limão","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":20},
  {"GROUP":"Tortas Geladas","ITEM":"Holandesa","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Tortas Geladas","ITEM":"Profiteroles","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":24},
  {"GROUP":"Vegetariano","ITEM":"Almondegas Vegetarianas","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Vermouth","ITEM":"Branco Doce","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Vermouth","ITEM":"Branco Seco","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Vermouth","ITEM":"Carpano Punt e Mes IT","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Vermouth","ITEM":"Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":15,"PRICE_MENU":15},
  {"GROUP":"Vinho","ITEM":"Alamos - Bod Catena Zapata 375ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":88,"PRICE_MENU":135},
  {"GROUP":"Vinho","ITEM":"Alamos - Bod Catena Zapata 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":121,"PRICE_MENU":169},
  {"GROUP":"Vinho","ITEM":"Alamos Seleccion - Bod Catena Zapata 750ml Tinto Pinot Noir","ACTIVE":"TRUE","PRICE_DELIVERY":170,"PRICE_MENU":215},
  {"GROUP":"Vinho","ITEM":"Alma Negra 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":218,"PRICE_MENU":276},
  {"GROUP":"Vinho","ITEM":"Amarone della Valpolicella 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":514,"PRICE_MENU":514},
  {"GROUP":"Vinho","ITEM":"Angelica Zapata 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":291,"PRICE_MENU":330},
  {"GROUP":"Vinho","ITEM":"Barbera d'Asti Batasiolo 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":111,"PRICE_MENU":156},
  {"GROUP":"Vinho","ITEM":"Bardolino Classico DOC 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":130,"PRICE_MENU":183},
  {"GROUP":"Vinho","ITEM":"Barolo 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":330,"PRICE_MENU":374},
  {"GROUP":"Vinho","ITEM":"Baron d'Arignac 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":56,"PRICE_MENU":87},
  {"GROUP":"Vinho","ITEM":"Baron Phillippe Rothschild Reserva 750ml Tinto Tempranillo","ACTIVE":"TRUE","PRICE_DELIVERY":60,"PRICE_MENU":92},
  {"GROUP":"Vinho","ITEM":"Bayanegra 750ml Tinto Tempranillo","ACTIVE":"TRUE","PRICE_DELIVERY":94,"PRICE_MENU":144},
  {"GROUP":"Vinho","ITEM":"Benjamim Nieto 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":49,"PRICE_MENU":75},
  {"GROUP":"Vinho","ITEM":"Bis Encostas de Estremoz-Alentejo 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":57,"PRICE_MENU":87},
  {"GROUP":"Vinho","ITEM":"Brunello di Montalcino 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":502,"PRICE_MENU":502},
  {"GROUP":"Vinho","ITEM":"Calamares 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":62,"PRICE_MENU":95},
  {"GROUP":"Vinho","ITEM":"Calamares 750ml Rosé","ACTIVE":"TRUE","PRICE_DELIVERY":62,"PRICE_MENU":95},
  {"GROUP":"Vinho","ITEM":"Caldirola Corte Antica 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 375ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":111},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":108,"PRICE_MENU":152},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":108,"PRICE_MENU":152},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Merlot","ACTIVE":"TRUE","PRICE_DELIVERY":108,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Carmen Insigne 750ml Syrah","ACTIVE":"TRUE","PRICE_DELIVERY":108,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Carmen Premier 750ml Pinot Noir","ACTIVE":"TRUE","PRICE_DELIVERY":151,"PRICE_MENU":212},
  {"GROUP":"Vinho","ITEM":"Casal Garcia 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":100},
  {"GROUP":"Vinho","ITEM":"Casal Garcia 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":65,"PRICE_MENU":100},
  {"GROUP":"Vinho","ITEM":"Casas  del Toqui 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":51,"PRICE_MENU":78},
  {"GROUP":"Vinho","ITEM":"Casas  del Toqui 750ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":51,"PRICE_MENU":78},
  {"GROUP":"Vinho","ITEM":"Casillero del Diablo 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":58,"PRICE_MENU":89},
  {"GROUP":"Vinho","ITEM":"Casillero del Diablo 750ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":58,"PRICE_MENU":89},
  {"GROUP":"Vinho","ITEM":"Catena Malbec- Bod Zapata 375ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":121,"PRICE_MENU":169},
  {"GROUP":"Vinho","ITEM":"Catena Malbec- Bod Zapata 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":206,"PRICE_MENU":261},
  {"GROUP":"Vinho","ITEM":"Cava Negra 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":54,"PRICE_MENU":83},
  {"GROUP":"Vinho","ITEM":"Chianti Gentilesco Bonacchi 375ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":102,"PRICE_MENU":157},
  {"GROUP":"Vinho","ITEM":"Chianti Gentilesco Bonacchi 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":143,"PRICE_MENU":200},
  {"GROUP":"Vinho","ITEM":"Chianti Ponte Vecchio Torciglione 3 litros Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":541,"PRICE_MENU":541},
  {"GROUP":"Vinho","ITEM":"Chianti Ruffino 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":104,"PRICE_MENU":159},
  {"GROUP":"Vinho","ITEM":"Concha y Toro - Reservado 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":35,"PRICE_MENU":54},
  {"GROUP":"Vinho","ITEM":"Copa Real Oro Tempranillo 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":94,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Corvo Bianco 375ml Branco","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Corvo Bianco 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":67,"PRICE_MENU":103},
  {"GROUP":"Vinho","ITEM":"Corvo Rosso 375ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":47,"PRICE_MENU":73},
  {"GROUP":"Vinho","ITEM":"Corvo Rosso 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":79,"PRICE_MENU":121},
  {"GROUP":"Vinho","ITEM":"Côtes du Rhône - Abel Pinchard 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":160,"PRICE_MENU":224},
  {"GROUP":"Vinho","ITEM":"D`Alamel 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":127,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"D´Alamel 750ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":127,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"D´Alamel 750ml Merlot","ACTIVE":"TRUE","PRICE_DELIVERY":127,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Dão Grao Vasco 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":64,"PRICE_MENU":98},
  {"GROUP":"Vinho","ITEM":"Dolcetto d'Alba DOC Batasiolo 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":118,"PRICE_MENU":166},
  {"GROUP":"Vinho","ITEM":"DV Catena 750ml Tinto Cabernet-Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":236,"PRICE_MENU":299},
  {"GROUP":"Vinho","ITEM":"Estiba 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":102,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Estiba 750ml Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":102,"PRICE_MENU":157},
  {"GROUP":"Vinho","ITEM":"Finca Flichman 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":63,"PRICE_MENU":96},
  {"GROUP":"Vinho","ITEM":"Finca La Daniela 750ml Tinto Malbec","ACTIVE":"TRUE","PRICE_DELIVERY":73,"PRICE_MENU":112},
  {"GROUP":"Vinho","ITEM":"Gato Negro 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":46,"PRICE_MENU":71},
  {"GROUP":"Vinho","ITEM":"Gato Negro 750ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":46,"PRICE_MENU":71},
  {"GROUP":"Vinho","ITEM":"IGT  Primitivo Puglia Bonacchi 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":120,"PRICE_MENU":168},
  {"GROUP":"Vinho","ITEM":"IGT Folino Capito  Vênezie 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":97,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"IGT Folino Capito 750ml Tinto Merlot\nerlot","ACTIVE":"TRUE","PRICE_DELIVERY":106,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Jarra 1L Vinho Nacional Seco","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":44},
  {"GROUP":"Vinho","ITEM":"Jarra 1L Vinho Nacional Suave","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":44},
  {"GROUP":"Vinho","ITEM":"Jarra 500ml Vinho Nacional Seco","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":27},
  {"GROUP":"Vinho","ITEM":"Jarra 500ml Vinho Nacional Suave","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":27},
  {"GROUP":"Vinho","ITEM":"La Camioneta 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":93,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Lagoalva 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":115,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Lambrusco Caravaggio 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":36,"PRICE_MENU":56},
  {"GROUP":"Vinho","ITEM":"Lambrusco Chiarelli 750ml","ACTIVE":"TRUE","PRICE_DELIVERY":36,"PRICE_MENU":56},
  {"GROUP":"Vinho","ITEM":"Lambrusco Donnelli 750ml","ACTIVE":"TRUE","PRICE_DELIVERY":36,"PRICE_MENU":56},
  {"GROUP":"Vinho","ITEM":"Leon Tarapaca 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":63,"PRICE_MENU":97},
  {"GROUP":"Vinho","ITEM":"Leon Tarapaca 750ml Tinto Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":63,"PRICE_MENU":97},
  {"GROUP":"Vinho","ITEM":"Macul Don Luis 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":107},
  {"GROUP":"Vinho","ITEM":"Mapema 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":157,"PRICE_MENU":220},
  {"GROUP":"Vinho","ITEM":"Marius Rouge 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":114,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Marques de Riscal Reserva 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":424,"PRICE_MENU":424},
  {"GROUP":"Vinho","ITEM":"Mateus Rosé 750ml Rosé","ACTIVE":"TRUE","PRICE_DELIVERY":68,"PRICE_MENU":105},
  {"GROUP":"Vinho","ITEM":"Montepulciano Nova Corte 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":97,"PRICE_MENU":149},
  {"GROUP":"Vinho","ITEM":"Montes Alpha 750ml Tinto Tempranillo","ACTIVE":"TRUE","PRICE_DELIVERY":252,"PRICE_MENU":286},
  {"GROUP":"Vinho","ITEM":"Nero D´Avola Bonacchi 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":115,"PRICE_MENU":161},
  {"GROUP":"Vinho","ITEM":"Periquita 375ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":43,"PRICE_MENU":66},
  {"GROUP":"Vinho","ITEM":"Periquita 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":71,"PRICE_MENU":110},
  {"GROUP":"Vinho","ITEM":"Pinot Grigio 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":114,"PRICE_MENU":160},
  {"GROUP":"Vinho","ITEM":"Posada Vieja 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":72,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Prosecco Sperone 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":118,"PRICE_MENU":165},
  {"GROUP":"Vinho","ITEM":"Rolha","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":50},
  {"GROUP":"Vinho","ITEM":"Rosso Piceno  (orgânico) 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":127,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Saccheto 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":106,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Saccheto 750ml Tinto Merlot","ACTIVE":"TRUE","PRICE_DELIVERY":106,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Salton Brut 375ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":34,"PRICE_MENU":52},
  {"GROUP":"Vinho","ITEM":"Salton Brut 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":42,"PRICE_MENU":64},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":27,"PRICE_MENU":41},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Malbec","ACTIVE":"FALSE","PRICE_DELIVERY":0,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Merlot","ACTIVE":"TRUE","PRICE_DELIVERY":27,"PRICE_MENU":41},
  {"GROUP":"Vinho","ITEM":"Salton Classic 750ml Tannat","ACTIVE":"TRUE","PRICE_DELIVERY":27,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":42,"PRICE_MENU":64},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Chardonay","ACTIVE":"TRUE","PRICE_DELIVERY":42,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Merlot","ACTIVE":"TRUE","PRICE_DELIVERY":42,"PRICE_MENU":64},
  {"GROUP":"Vinho","ITEM":"Salton Paradoxo 750ml Pinot Noir","ACTIVE":"TRUE","PRICE_DELIVERY":42,"PRICE_MENU":64},
  {"GROUP":"Vinho","ITEM":"Salton Prosecco Brut 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":42,"PRICE_MENU":64},
  {"GROUP":"Vinho","ITEM":"Sangiovese Bonacchi 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":108,"PRICE_MENU":152},
  {"GROUP":"Vinho","ITEM":"Santa Alvara 750ml Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":89,"PRICE_MENU":137},
  {"GROUP":"Vinho","ITEM":"Santa Alvara 750ml Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":89,"PRICE_MENU":137},
  {"GROUP":"Vinho","ITEM":"Santa Carolina Reservado 750ml Tinto Carmenere","ACTIVE":"TRUE","PRICE_DELIVERY":40,"PRICE_MENU":62},
  {"GROUP":"Vinho","ITEM":"Santa Helena 375ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":24,"PRICE_MENU":36},
  {"GROUP":"Vinho","ITEM":"Santa Helena 750ml Branco","ACTIVE":"TRUE","PRICE_DELIVERY":39,"PRICE_MENU":60},
  {"GROUP":"Vinho","ITEM":"Santa Helena 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":39,"PRICE_MENU":60},
  {"GROUP":"Vinho","ITEM":"Santo Cristo Amphora Garnacha 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":98,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Taça 250ml Caldirola Corte Antica Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":25},
  {"GROUP":"Vinho","ITEM":"Taça 250ml Vinho Nacional Seco","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Vinho","ITEM":"Taça 250ml Vinho Nacional Suave","ACTIVE":"TRUE","PRICE_DELIVERY":0,"PRICE_MENU":17},
  {"GROUP":"Vinho","ITEM":"Tarapaca Cosecha 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":47,"PRICE_MENU":72},
  {"GROUP":"Vinho","ITEM":"Uxmal 750ml Tinto Malbec-Syrah","ACTIVE":"TRUE","PRICE_DELIVERY":104,"PRICE_MENU":160},
  {"GROUP":"Vinho","ITEM":"Valdemoreda 750ml Tinto Tempranillo","ACTIVE":"TRUE","PRICE_DELIVERY":102,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Vallontano 750ml Tinto Cabernet Sauvignon","ACTIVE":"TRUE","PRICE_DELIVERY":89,"PRICE_MENU":0},
  {"GROUP":"Vinho","ITEM":"Valpolicella Bolla 375ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":70,"PRICE_MENU":108},
  {"GROUP":"Vinho","ITEM":"Valpolicella Bolla 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":91,"PRICE_MENU":140},
  {"GROUP":"Vinho","ITEM":"Valpolicella Ripasso Class Superiore 750ml Tinto","ACTIVE":"TRUE","PRICE_DELIVERY":267,"PRICE_MENU":302},
  {"GROUP":"Vodkas","ITEM":"Absolut","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Vodkas","ITEM":"Smirnoff","ACTIVE":"TRUE","PRICE_DELIVERY":20,"PRICE_MENU":20},
  {"GROUP":"Vodkas","ITEM":"Stolichnaya","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Whikies","ITEM":"Chivas 12 anos","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Whikies","ITEM":"J. B.","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25},
  {"GROUP":"Whikies","ITEM":"Jack Daniels","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Whikies","ITEM":"Johnnie Walker Black Label","ACTIVE":"TRUE","PRICE_DELIVERY":30,"PRICE_MENU":30},
  {"GROUP":"Whikies","ITEM":"Johnnie Walker Red Label","ACTIVE":"TRUE","PRICE_DELIVERY":25,"PRICE_MENU":25}
];

export default dadosDeliveryItems;